/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Popups;

import Entidades.*;
import AccesoADatos.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class popupActivarAloja extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla = new DefaultTableModel();

    /**
     * Creates new form popupCiudad
     */
    public popupActivarAloja() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana
        crearTable();
        llenarTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alojaTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        setMaximumSize(new java.awt.Dimension(570, 420));
        setMinimumSize(new java.awt.Dimension(570, 420));
        setPreferredSize(new java.awt.Dimension(570, 420));
        getContentPane().setLayout(null);

        selectButton.setText("Activar");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(selectButton);
        selectButton.setBounds(320, 340, 140, 25);

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salirButton);
        salirButton.setBounds(90, 340, 70, 25);

        alojaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        alojaTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(alojaTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 550, 290);

        setBounds(115, 90, 570, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        int id = Integer.valueOf(modeloTabla.getValueAt(alojaTable.getSelectedRow(), 0).toString());
        Disponible_Data ok = new Disponible_Data();
        ok.activarAlojamiento(id);
        ClearTable();
        llenarTable();
    }//GEN-LAST:event_selectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alojaTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables

    private void crearTable() {
        modeloTabla.addColumn("idAlojamiento");
        modeloTabla.addColumn("Localidad");
        modeloTabla.addColumn("Tipo Alojamiento");
        modeloTabla.addColumn("Servicio");
        modeloTabla.addColumn("Precio por Día");
        alojaTable.setModel(modeloTabla);
    }

    private void llenarTable() {
        List<Alojamiento> lista = new ArrayList<>();
        Disponible_Data inactivas = new Disponible_Data();
        lista = inactivas.listarInactivos();
        for (Alojamiento al : lista) {
            modeloTabla.addRow(new Object[]{al.getIdAlojamiento(), al.getCiudadDest().getNombre(), al.getTipoAlojamiento(), al.getTipoServicio(), al.getImporteDiario()});
        }
    }

    private void ClearTable() {
        for (int i = 0; i < alojaTable.getRowCount(); i++) {
            modeloTabla.removeRow(i);
            i -= 1;
        }
    }
}
