/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Popups;

import AccesoADatos.*;
import Entidades.*;
import Vistas.VentanaPresupuesto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public final class popupPresupuestosA extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla = new DefaultTableModel() {
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };

    /**
     * Creates new form popupPasajes
     */
    public popupPresupuestosA() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana
        crearTabla();
        String p = buscarProvincia();
        listarAlojamientos(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        alojamientosTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(332, 200));
        setMinimumSize(new java.awt.Dimension(332, 200));
        setPreferredSize(new java.awt.Dimension(332, 200));

        alojamientosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        alojamientosTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        alojamientosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alojamientosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(alojamientosTable);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cruz.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(190, 230, 332, 200);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void alojamientosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alojamientosTableMouseClicked
        VentanaPresupuesto.jTFAl1.setText(modeloTabla.getValueAt(alojamientosTable.getSelectedRow(), 1).toString());
        VentanaPresupuesto.jTFAl2.setText(modeloTabla.getValueAt(alojamientosTable.getSelectedRow(), 2).toString());
        VentanaPresupuesto.jTFAl3.setText(modeloTabla.getValueAt(alojamientosTable.getSelectedRow(), 3).toString());
        Disponible_Data buscar = new Disponible_Data();
        VentanaPresupuesto.alojamientoPaquete = buscar.buscarAlojamiento(Integer.parseInt(modeloTabla.getValueAt(alojamientosTable.getSelectedRow(), 4).toString()));
        VentanaPresupuesto.jLAclaracion1.setVisible(true);
        VentanaPresupuesto.checkIN.setEnabled(true);
        VentanaPresupuesto.checkOUT.setEnabled(true);
        VentanaPresupuesto.jTFCantidadPasajeros.setEditable(true);
        VentanaPresupuesto.jTFCantidadPasajeros.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_alojamientosTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alojamientosTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void crearTabla() {
        modeloTabla.addColumn("Ciudad");
        modeloTabla.addColumn("Tipo Alojamiento");
        modeloTabla.addColumn("Servicio");
        modeloTabla.addColumn("Precio por Día");
        modeloTabla.addColumn("ID Alojamiento");
        alojamientosTable.setModel(modeloTabla);

    }

    private String buscarProvincia() {
        String provincia;
        Ciudad_Data cd = new Ciudad_Data();
        Ciudad c = cd.buscarCiudad(Integer.parseInt(VentanaPresupuesto.idCD.getText()));
        provincia = c.getProvincia();
        return provincia;
    }

    public void listarAlojamientos(String p) {
        Disponible_Data listar = new Disponible_Data();
        List<Alojamiento> list = new ArrayList();
        list = listar.listarPorProvincia(p);
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existen alojamientos dentro de esta provincia.");
            VentanaPresupuesto.bloquearCampos();
            VentanaPresupuesto.limpiarCampos();
            VentanaPresupuesto.jBCD.setEnabled(true);
        } else {
            for (Alojamiento al : list) {
                modeloTabla.addRow(new Object[]{al.getCiudadDest().getNombre(), al.getTipoAlojamiento(), al.getTipoServicio(), al.getImporteDiario(), al.getIdAlojamiento()});
            }
        }
    }

}
