package Vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import AccesoADatos.*;
import Entidades.*;

/**
 *
 * @author Susana
 */
public class VentanaPaquete extends javax.swing.JInternalFrame {

    private Pasaje_Data pasajeData = new Pasaje_Data();
    private Pasaje pasaje = null;
    private Ciudad ciudad = new Ciudad();
    private Ciudad_Data ciudadData = new Ciudad_Data();
    private Alojamiento_Data alojamientoData = new Alojamiento_Data();
    private Alojamiento alojamiento = null;
    private Paquete_Data paqueteData = new Paquete_Data();
    private Paquete paquete;

    /**
     * Creates new form VentanaPaquete
     */
    public VentanaPaquete() {
        initComponents();
        desactivarCampos();
        jTIdPaquete.setEnabled(true);
        jBotonModificar.setEnabled(false);
        jBotonEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLIdPaquete = new javax.swing.JLabel();
        jTIdPaquete = new javax.swing.JTextField();
        jBotonBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTIdCiudadOrigen = new javax.swing.JTextField();
        jTIdCiudadDestino = new javax.swing.JTextField();
        jLIdCiudadDestino = new javax.swing.JLabel();
        jLNombreOrigen = new javax.swing.JLabel();
        jTNombreOrigen = new javax.swing.JTextField();
        jLNombreDestino = new javax.swing.JLabel();
        jTNombreDestino = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLIdAlojamiento = new javax.swing.JLabel();
        jTIdAlojamiento = new javax.swing.JTextField();
        jLTipoAlojamiento = new javax.swing.JLabel();
        jTTipoAlojamiento = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLIdPasaje = new javax.swing.JLabel();
        jTIdPasaje = new javax.swing.JTextField();
        jLTipoTransporte = new javax.swing.JLabel();
        jTTipoTransporte = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jBotonNuevo = new javax.swing.JButton();
        jBotonGuardar = new javax.swing.JButton();
        jBotonModificar = new javax.swing.JButton();
        jBotonSalir = new javax.swing.JButton();
        jBotonEliminar = new javax.swing.JButton();

        setTitle("Paquete");

        jLIdPaquete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLIdPaquete.setText("ID Paquete: ");

        jTIdPaquete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jBotonBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonBuscar.setText("Buscar");
        jBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Id Ciudad Origen: ");

        jTIdCiudadOrigen.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTIdCiudadDestino.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLIdCiudadDestino.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLIdCiudadDestino.setText("Id Ciudad Destino: ");

        jLNombreOrigen.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLNombreOrigen.setText("Nombre Origen: ");

        jTNombreOrigen.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLNombreDestino.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLNombreDestino.setText("Nombre Destino: ");

        jTNombreDestino.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(jTIdCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLIdCiudadDestino)
                        .addGap(18, 18, 18)
                        .addComponent(jTIdCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLNombreOrigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTNombreOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLNombreDestino)
                        .addGap(18, 18, 18)
                        .addComponent(jTNombreDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombreDestino)
                            .addComponent(jTIdCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLIdCiudadDestino))
                        .addGap(103, 103, 103))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTNombreOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTIdCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLNombreOrigen)))
                        .addGap(18, 18, 18)
                        .addComponent(jTNombreDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));

        jLIdAlojamiento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLIdAlojamiento.setText("Id Alojamiento: ");

        jTIdAlojamiento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLTipoAlojamiento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLTipoAlojamiento.setText("Tipo Alojamiento: ");

        jTTipoAlojamiento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLIdAlojamiento)
                .addGap(27, 27, 27)
                .addComponent(jTIdAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLTipoAlojamiento)
                .addGap(37, 37, 37)
                .addComponent(jTTipoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIdAlojamiento)
                    .addComponent(jTIdAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTipoAlojamiento)
                    .addComponent(jTTipoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLIdPasaje.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLIdPasaje.setText("Id Pasaje: ");

        jTIdPasaje.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLTipoTransporte.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLTipoTransporte.setText("Tipo Transporte: ");

        jTTipoTransporte.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLIdPasaje)
                .addGap(27, 27, 27)
                .addComponent(jTIdPasaje, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLTipoTransporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTTipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIdPasaje)
                    .addComponent(jTIdPasaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTipoTransporte)
                    .addComponent(jTTipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jBotonNuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonNuevo.setText("Nuevo");
        jBotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonNuevoActionPerformed(evt);
            }
        });

        jBotonGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonGuardar.setText("Guardar");
        jBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonGuardarActionPerformed(evt);
            }
        });

        jBotonModificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonModificar.setText("Modificar");

        jBotonSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonSalir.setText("Salir");
        jBotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSalirActionPerformed(evt);
            }
        });

        jBotonEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBotonNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBotonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBotonModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonSalir)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonNuevo)
                    .addComponent(jBotonGuardar)
                    .addComponent(jBotonModificar)
                    .addComponent(jBotonSalir)
                    .addComponent(jBotonEliminar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLIdPaquete)
                        .addGap(24, 24, 24)
                        .addComponent(jTIdPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBotonBuscar)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIdPaquete)
                    .addComponent(jTIdPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonBuscar))
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBotonSalirActionPerformed

    private void jBotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonNuevoActionPerformed
        activarCampos();
        limpiarCampos();
        paquete = null;
        jTIdPaquete.setEnabled(false);
        jBotonNuevo.setEnabled(true);
        jBotonGuardar.setEnabled(true);
        jBotonEliminar.setEnabled(false);
        jBotonModificar.setEnabled(false); 
    }//GEN-LAST:event_jBotonNuevoActionPerformed

    private void jBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonGuardarActionPerformed
      
        
    }//GEN-LAST:event_jBotonGuardarActionPerformed

    private void jBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarActionPerformed
        try{
            Integer id=Integer.parseInt(jTIdPaquete.getText()); 
            paquete=paqueteData.buscarPaquete2(id);
            if(paquete != null){
                jTIdCiudadOrigen.setText(paquete.getOrigen().getIdCiudad()+"");
                jTNombreOrigen.setText(paquete.getOrigen().getNombre());
                jTIdCiudadDestino.setText(paquete.getDestino().getIdCiudad()+"");
                jTNombreDestino.setText(paquete.getDestino().getNombre());
                jTIdAlojamiento.setText(paquete.getAlojamiento().getIdAlojamiento()+"");
                jTTipoAlojamiento.setText(paquete.getAlojamiento().getTipoAlojamiento());
                jTIdPasaje.setText(paquete.getPasaje().getIdPasajero()+"");
                jTTipoTransporte.setText(paquete.getPasaje().getTipoTransporte());
               }
               
        }catch(NumberFormatException es){
         JOptionPane.showMessageDialog(this, "Debe ingresar un ID valido");}
    }//GEN-LAST:event_jBotonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonBuscar;
    private javax.swing.JButton jBotonEliminar;
    private javax.swing.JButton jBotonGuardar;
    private javax.swing.JButton jBotonModificar;
    private javax.swing.JButton jBotonNuevo;
    private javax.swing.JButton jBotonSalir;
    private javax.swing.JLabel jLIdAlojamiento;
    private javax.swing.JLabel jLIdCiudadDestino;
    private javax.swing.JLabel jLIdPaquete;
    private javax.swing.JLabel jLIdPasaje;
    private javax.swing.JLabel jLNombreDestino;
    private javax.swing.JLabel jLNombreOrigen;
    private javax.swing.JLabel jLTipoAlojamiento;
    private javax.swing.JLabel jLTipoTransporte;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTIdAlojamiento;
    private javax.swing.JTextField jTIdCiudadDestino;
    private javax.swing.JTextField jTIdCiudadOrigen;
    private javax.swing.JTextField jTIdPaquete;
    private javax.swing.JTextField jTIdPasaje;
    private javax.swing.JTextField jTNombreDestino;
    private javax.swing.JTextField jTNombreOrigen;
    private javax.swing.JTextField jTTipoAlojamiento;
    private javax.swing.JTextField jTTipoTransporte;
    // End of variables declaration//GEN-END:variables

    public void desactivarCampos() {

        jTIdPasaje.setEnabled(false);
        jTIdPaquete.setEnabled(false);
        jTIdCiudadOrigen.setEnabled(false);
        jTIdCiudadDestino.setEnabled(false);
        jTIdAlojamiento.setEnabled(false);
    }

    public void activarCampos() {
        jTIdPasaje.setEnabled(true);
        jTIdPaquete.setEnabled(true);
        jTIdCiudadOrigen.setEnabled(true);
        jTIdCiudadDestino.setEnabled(true);
        jTIdAlojamiento.setEnabled(true);

    }

    public void limpiarCampos() {
        jTIdPasaje.setText("");
        jTTipoAlojamiento.setText("");
        jTIdPaquete.setText("");
        jTIdCiudadOrigen.setText("");
        jTNombreOrigen.setText("");
        jTIdCiudadDestino.setText("");
        jTNombreDestino.setText("");
        jTTipoAlojamiento.setText("");
        jTIdAlojamiento.setText("");
    }
}
