package Vistas;

import AccesoADatos.*;
import Entidades.*;
import Vistas.*;
import com.sun.glass.events.KeyEvent;
import static java.awt.SystemColor.text;
import java.sql.*;
import java.time.*;
import java.util.*;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author Susana
 */
public class VentanaCiudad extends javax.swing.JInternalFrame {

    private Ciudad_Data ciudadData = new Ciudad_Data();
    private Ciudad ciudad = null;

    /**
     * Creates new form ciudad
     */
    public VentanaCiudad() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana
        desactivarCampos();
        jTId.setEnabled(true);
        jBotonGuardar.setEnabled(false);
        jBotonEliminar.setEnabled(false);
        jBotonModificar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLId = new javax.swing.JLabel();
        jTId = new javax.swing.JTextField();
        jBotonBuscar = new javax.swing.JButton();
        jLProvincia = new javax.swing.JLabel();
        jLPais = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTProvincia = new javax.swing.JTextField();
        jTPais = new javax.swing.JTextField();
        jBotonModificar = new javax.swing.JButton();
        jBotonNuevo = new javax.swing.JButton();
        jBotonGuardar = new javax.swing.JButton();
        jBotonEliminar = new javax.swing.JButton();
        jBotonActivar = new javax.swing.JButton();
        panelLateral2Ciudad = new javax.swing.JPanel();
        closeCiudad = new javax.swing.JButton();
        panelLateral1Ciudad = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 280, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setTitle("Ciudad");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jDesktopPane2.setMaximumSize(new java.awt.Dimension(800, 600));
        jDesktopPane2.setMinimumSize(new java.awt.Dimension(800, 600));

        jLId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLId.setText("Id: ");
        jDesktopPane2.add(jLId);
        jLId.setBounds(290, 220, 21, 17);

        jTId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTIdKeyTyped(evt);
            }
        });
        jDesktopPane2.add(jTId);
        jTId.setBounds(330, 220, 118, 23);

        jBotonBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonBuscar.setText("Buscar");
        jBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jBotonBuscar);
        jBotonBuscar.setBounds(680, 190, 90, 31);

        jLProvincia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLProvincia.setText("Provincia:");
        jDesktopPane2.add(jLProvincia);
        jLProvincia.setBounds(290, 320, 70, 17);

        jLPais.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLPais.setText("Pais:");
        jDesktopPane2.add(jLPais);
        jLPais.setBounds(290, 360, 33, 17);

        jLNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLNombre.setText("Nombre:");
        jDesktopPane2.add(jLNombre);
        jLNombre.setBounds(290, 270, 59, 17);

        jTNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreKeyTyped(evt);
            }
        });
        jDesktopPane2.add(jTNombre);
        jTNombre.setBounds(380, 270, 227, 23);

        jTProvincia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTProvincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTProvinciaKeyTyped(evt);
            }
        });
        jDesktopPane2.add(jTProvincia);
        jTProvincia.setBounds(380, 310, 227, 23);

        jTPais.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPaisKeyTyped(evt);
            }
        });
        jDesktopPane2.add(jTPais);
        jTPais.setBounds(380, 360, 227, 23);

        jBotonModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonModificar.setText("Modificar");
        jBotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonModificarActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jBotonModificar);
        jBotonModificar.setBounds(510, 450, 100, 31);

        jBotonNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonNuevo.setText("Nuevo");
        jBotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonNuevoActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jBotonNuevo);
        jBotonNuevo.setBounds(320, 450, 80, 31);

        jBotonGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonGuardar.setText("Guardar");
        jBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonGuardarActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jBotonGuardar);
        jBotonGuardar.setBounds(410, 450, 90, 31);

        jBotonEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonEliminar.setText("Eliminar");
        jBotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEliminarActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jBotonEliminar);
        jBotonEliminar.setBounds(620, 450, 90, 31);

        jBotonActivar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonActivar.setText("Activar");
        jBotonActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonActivarActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jBotonActivar);
        jBotonActivar.setBounds(680, 320, 90, 31);

        panelLateral2Ciudad.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout panelLateral2CiudadLayout = new javax.swing.GroupLayout(panelLateral2Ciudad);
        panelLateral2Ciudad.setLayout(panelLateral2CiudadLayout);
        panelLateral2CiudadLayout.setHorizontalGroup(
            panelLateral2CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        panelLateral2CiudadLayout.setVerticalGroup(
            panelLateral2CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jDesktopPane2.add(panelLateral2Ciudad);
        panelLateral2Ciudad.setBounds(0, 170, 229, 430);

        closeCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flechaAtras.png"))); // NOI18N
        closeCiudad.setText("Atrás");
        closeCiudad.setAlignmentY(0.0F);
        closeCiudad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCiudadActionPerformed(evt);
            }
        });
        jDesktopPane2.add(closeCiudad);
        closeCiudad.setBounds(670, 20, 90, 38);

        panelLateral1Ciudad.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo2.png"))); // NOI18N

        javax.swing.GroupLayout panelLateral1CiudadLayout = new javax.swing.GroupLayout(panelLateral1Ciudad);
        panelLateral1Ciudad.setLayout(panelLateral1CiudadLayout);
        panelLateral1CiudadLayout.setHorizontalGroup(
            panelLateral1CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        panelLateral1CiudadLayout.setVerticalGroup(
            panelLateral1CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );

        jDesktopPane2.add(panelLateral1Ciudad);
        panelLateral1Ciudad.setBounds(0, 0, 229, 171);

        jLabel1.setFont(new java.awt.Font("Broadway", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CIUDADES");
        jDesktopPane2.add(jLabel1);
        jLabel1.setBounds(400, 50, 160, 50);

        clearButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clearButton.setText("Limpiar");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jDesktopPane2.add(clearButton);
        clearButton.setBounds(680, 230, 90, 31);

        getContentPane().add(jDesktopPane2);
        jDesktopPane2.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarActionPerformed

        try {
            activarCampos();
            Ciudad ciud = new Ciudad();
            int id = Integer.parseInt(jTId.getText());
            ciud = ciudadData.buscarCiudad(id);
            if (ciud != null) {
                jTProvincia.setText(ciud.getProvincia());
                jTNombre.setText(ciud.getNombre());
                jTPais.setText(ciud.getPais());
                jBotonGuardar.setEnabled(true);
                jBotonEliminar.setEnabled(true);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar solo números para el Id ");
            jTId.requestFocus();
            limpiarCampos();
            jBotonGuardar.setEnabled(false);
        } catch (NullPointerException ex) {

        }
        jTId.setEnabled(true);
        jBotonModificar.setEnabled(true);
        jBotonGuardar.setEnabled(false);
        jBotonNuevo.setEnabled(true);

    }//GEN-LAST:event_jBotonBuscarActionPerformed

    private void jBotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonNuevoActionPerformed
        activarCampos();
        limpiarCampos();
        ciudad = null;
        jTId.setEnabled(false);
        jBotonNuevo.setEnabled(true);
        jBotonGuardar.setEnabled(true);
        jBotonEliminar.setEnabled(false);
        jBotonModificar.setEnabled(false);
        jBotonActivar.setEnabled(false);

    }//GEN-LAST:event_jBotonNuevoActionPerformed

    private void jBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonGuardarActionPerformed

        try {
            jTId.setEnabled(false);
            String nombre = jTNombre.getText();
            String provincia = jTProvincia.getText();
            String pais = jTPais.getText();
            if (nombre.isEmpty() || provincia.isEmpty()) {
                JOptionPane.showMessageDialog(this, " No debe haber campos vacios");
                return;
            }
            if (Pattern.matches("^[a-zA-Z ]*$", provincia)) {
                if (Pattern.matches("^[a-zA-Z ]*$", nombre)) {
                    if (Pattern.matches("^[a-zA-Z ]*$", pais)) {
                        if (ciudad == null) {

                            ciudad = new Ciudad(nombre, provincia, pais, true);
                            ciudadData.guardarCiudad(ciudad);;
                            jBotonNuevo.setSelected(false);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "En el Pais solo puede ingresar letras");
                        jTPais.requestFocus();
                        jTPais.setText("");

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "En el nombre de la Ciudad solo puede ingresar letras");
                    jTNombre.requestFocus();
                    jTNombre.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "En la Provincia solo puede ingresar letras");
                jTProvincia.requestFocus();
                jTProvincia.setText("");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un Id valido ");
        }
        limpiarCampos();
        desactivarCampos();
        jTId.requestFocus();
        jTId.setEnabled(true);
        jBotonNuevo.setEnabled(true);
        jBotonNuevo.setSelected(false);

    }//GEN-LAST:event_jBotonGuardarActionPerformed

    private void jBotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEliminarActionPerformed
        Ciudad cuidad;
        ciudad = null;
        int id = Integer.parseInt(jTId.getText());
        String nombre = jTNombre.getText();
        String provincia = jTProvincia.getText();
        String pais = jTPais.getText();

        if (ciudad == null) {
            ciudad = new Ciudad(id, nombre, provincia, pais, false);
            int respuesta = JOptionPane.showConfirmDialog(null, "Esta por borrar una ciudad ¿Quieres continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                ciudadData.eliminarCiudad(ciudad);
                limpiarCampos();
                activarCampos();
                jTId.requestFocus();
            }
        }
    }//GEN-LAST:event_jBotonEliminarActionPerformed

    private void jBotonActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonActivarActionPerformed
//        ciudadData.ActivarCiudad();
//        JOptionPane.showMessageDialog(this, "Todas las ciudades estan activas");
        jDesktopPane2.repaint();
        popupCiudad popupCity = new popupCiudad();
        popupCity.setVisible(true);
        jDesktopPane2.add(popupCity);
        jDesktopPane2.moveToFront(popupCity);

    }//GEN-LAST:event_jBotonActivarActionPerformed

    private void jBotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonModificarActionPerformed
        Ciudad ciudad = new Ciudad();
        try {

            Integer id = Integer.parseInt(jTId.getText());
            jTId.setEnabled(false);
            String nombre = jTNombre.getText();
            String provincia = jTProvincia.getText();
            String pais = jTPais.getText();
            if (nombre.isEmpty() || provincia.isEmpty()) {
                JOptionPane.showMessageDialog(this, " No debe haber campos vacios");
                return;
            }
            if (Pattern.matches("^[a-zA-Z ]*$", provincia)) {
                if (Pattern.matches("^[a-zA-Z ]*$", nombre)) {
                    if (Pattern.matches("^[a-zA-Z ]*$", pais)) {
                        Ciudad ciuda = ciudadData.buscarCiudad(id);
                        if (id == ciuda.getIdCiudad()) {
                            ciuda.getIdCiudad();
                            ciuda.setNombre(nombre);
                            ciuda.setProvincia(provincia);
                            ciuda.setPais(pais);
                            ciudadData.modificarCiudad(ciuda);
                            jBotonNuevo.setEnabled(true);

                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "En el Pais solo puede ingresar letras");
                        jTPais.requestFocus();
                        jTPais.setText("");

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "En el nombre de la Ciudad solo puede ingresar letras");
                    jTNombre.requestFocus();
                    jTNombre.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "En la Provincia solo puede ingresar letras");
                jTProvincia.requestFocus();
                jTProvincia.setText("");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un documento valido ");
        }
        limpiarCampos();
        desactivarCampos();
        jTId.requestFocus();
        jTId.setEnabled(true);
        jBotonNuevo.setEnabled(true);
        jBotonNuevo.setSelected(false);
    }//GEN-LAST:event_jBotonModificarActionPerformed

    private void closeCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCiudadActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeCiudadActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        desactivarCampos();
        jTId.setEnabled(true);
        jBotonGuardar.setEnabled(false);
        jBotonEliminar.setEnabled(false);
        jBotonModificar.setEnabled(false);
        jBotonActivar.setEnabled(true);
        jTId.setText("");
        jTNombre.setText("");
        jTPais.setText("");
        jTProvincia.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jTIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIdKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTIdKeyTyped

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyTyped
        char caracter = evt.getKeyChar();
        if (!(caracter < '0' || caracter > '9') && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTNombreKeyTyped

    private void jTProvinciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTProvinciaKeyTyped
        char caracter = evt.getKeyChar();
        if (!(caracter < '0' || caracter > '9') && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTProvinciaKeyTyped

    private void jTPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPaisKeyTyped
        char caracter = evt.getKeyChar();
        if (!(caracter < '0' || caracter > '9') && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTPaisKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeCiudad;
    private javax.swing.JButton jBotonActivar;
    private javax.swing.JButton jBotonBuscar;
    private javax.swing.JButton jBotonEliminar;
    private javax.swing.JButton jBotonGuardar;
    private javax.swing.JButton jBotonModificar;
    private javax.swing.JButton jBotonNuevo;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPais;
    private javax.swing.JLabel jLProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTId;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPais;
    private javax.swing.JTextField jTProvincia;
    private javax.swing.JPanel panelLateral1Ciudad;
    private javax.swing.JPanel panelLateral2Ciudad;
    // End of variables declaration//GEN-END:variables

    public void desactivarCampos() {

        jTProvincia.setEnabled(false);
        jTPais.setEnabled(false);
        jTNombre.setEnabled(false);

    }

    public void activarCampos() {
        jTId.setEnabled(true);
        jTNombre.setEnabled(true);
        jTPais.setEnabled(true);
        jTProvincia.setEnabled(true);

    }

    public void limpiarCampos() {
        jTId.setText("");
        jTNombre.setText("");
        jTProvincia.setText("");
        jTPais.setText("");
    }
}
