
package Vistas;

import java.awt.*;
import java.sql.Date;
import java.time.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import AccesoADatos.*;
import Entidades.*;
import java.util.*;
import com.toedter.calendar.JDateChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Susana
 */
public class VentanaPresupuesto extends javax.swing.JInternalFrame {
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private Ciudad_Data ciudadData =new Ciudad_Data();
    private Ciudad ciudad = new Ciudad();
    private Alojamiento alojamiento =new Alojamiento();
    private Alojamiento_Data alojamientoData =new Alojamiento_Data();

    /**
     * Creates new form VentanaPresupuesto
     */
    public VentanaPresupuesto() {
        initComponents();
     //   setIconImage(getIconImage());
        cargarComboCiudad();
        cargarComboTransporte();
        cargarComboTipoAlojamiento();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAlojamiento = new javax.swing.JLabel();
        jComboAlojamiento = new javax.swing.JComboBox<>();
        jLCantPasajeros = new javax.swing.JLabel();
        jSCantPasajeros = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaPresupuesto = new javax.swing.JTable();
        jBotonModificar = new javax.swing.JButton();
        jBotonPresupuesto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLFechaIngreso = new javax.swing.JLabel();
        jDateFechaIngreso = new com.toedter.calendar.JDateChooser();
        jDateFechaEgreso = new com.toedter.calendar.JDateChooser();
        jLFechaIngreso1 = new javax.swing.JLabel();
        jLTemporada = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLCiudadOrigen = new javax.swing.JLabel();
        jComboCiudadOrigen = new javax.swing.JComboBox<>();
        jComboCiudadDestino = new javax.swing.JComboBox<>();
        jLCiudadOrigen1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLTipoTransporte = new javax.swing.JLabel();
        jComboTipoTransporte = new javax.swing.JComboBox<>();
        jLTipoTransporte1 = new javax.swing.JLabel();
        jComboTipoAlojamiento = new javax.swing.JComboBox<>();

        setTitle("Presupuesto");

        jLAlojamiento.setText("Alojamiento");

        jLCantPasajeros.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLCantPasajeros.setText("Cantidad de pasajeros: ");

        jScrollPane2.setViewportView(jTablaPresupuesto);

        jBotonModificar.setText("modificar");

        jBotonPresupuesto.setText("Presupuesto");
        jBotonPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonPresupuestoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLFechaIngreso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLFechaIngreso.setText("Fecha Ingreso: ");

        jDateFechaIngreso.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateFechaIngresoPropertyChange(evt);
            }
        });

        jLFechaIngreso1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLFechaIngreso1.setText("Fecha Egreso:  ");

        jLTemporada.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTemporada.setForeground(new java.awt.Color(0, 51, 153));
        jLTemporada.setText("TEMPORADA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLFechaIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jDateFechaEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFechaIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateFechaEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLFechaIngreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateFechaIngreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jLTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLCiudadOrigen.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLCiudadOrigen.setText("Ciudad Origen: ");

        jComboCiudadOrigen.setMinimumSize(new java.awt.Dimension(30, 20));

        jComboCiudadDestino.setPreferredSize(new java.awt.Dimension(30, 20));
        jComboCiudadDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCiudadDestinoActionPerformed(evt);
            }
        });

        jLCiudadOrigen1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLCiudadOrigen1.setText("Ciudad Destino: ");

        jLTipoTransporte.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLTipoTransporte.setText("Tipo Transporte: ");

        jLTipoTransporte1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLTipoTransporte1.setText("Tipo Alojamiento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTipoTransporte)
                .addGap(78, 78, 78)
                .addComponent(jComboTipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTipoTransporte1)
                .addGap(48, 48, 48)
                .addComponent(jComboTipoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTipoTransporte)
                    .addComponent(jLTipoTransporte1)
                    .addComponent(jComboTipoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCiudadOrigen)
                .addGap(62, 62, 62)
                .addComponent(jComboCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLCiudadOrigen1)
                .addGap(34, 34, 34)
                .addComponent(jComboCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCiudadOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCiudadOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLAlojamiento))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLCantPasajeros)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSCantPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(235, 235, 235)
                                .addComponent(jBotonPresupuesto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jComboAlojamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBotonModificar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAlojamiento)
                    .addComponent(jComboAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCantPasajeros)
                    .addComponent(jSCantPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonPresupuesto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBotonModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDateFechaIngresoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateFechaIngresoPropertyChange
        try{
            LocalDate fechaI = jDateFechaIngreso.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            //LocalDate fechaE = jDateFechaEgreso.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            int mes;
            mes = fechaI.getMonthValue();
            if (mes == 01 || mes == 07) {
                jLTemporada.setText("Temporada Alta");
                //  JTTemporada.="temporada ALta;";
            } else if (mes == 02 || mes == 06) {
                jLTemporada.setText("Temporada Media");
            } else {
                jLTemporada.setText("Temporada Baja");
            }
        }catch(NullPointerException ex){
            if (jDateFechaIngreso.getDate()==null){
                JOptionPane.showMessageDialog(this,"Debe ingresar la fecha de Ingreso");}
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jDateFechaIngresoPropertyChange

    private void jComboCiudadDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCiudadDestinoActionPerformed

        Ciudad ciudadSelec=(Ciudad) jComboCiudadDestino.getSelectedItem();

        List<Alojamiento> aloj = alojamientoData.seleccionarAlojamiento( ciudadSelec.getProvincia());
        for (Alojamiento alojamientos : aloj) {
            //cargar el combo de alojamientos
            jComboAlojamiento.addItem(new Alojamiento(alojamientos.getIdAlojamiento(),alojamiento.getTipoAlojamiento(),alojamiento.getFechaIn(),alojamiento.getFechaOut(),true,alojamiento.getTipoServicio(),alojamiento.getImporteDiario(),alojamiento.getCiudadDest()));
        }
    }//GEN-LAST:event_jComboCiudadDestinoActionPerformed

    private void jBotonPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonPresupuestoActionPerformed
        try{
            //calcular dias
            java.util.Date fecha1 = jDateFechaIngreso.getDate();
            java.util.Date fecha2 = jDateFechaEgreso.getDate();
            java.util.Calendar calendar1 = java.util.Calendar.getInstance();
            calendar1.setTime(fecha1);
            java.util.Calendar calendar2 = java.util.Calendar.getInstance();
            calendar2.setTime(fecha2);
            long diferencia = calendar2.getTimeInMillis() - calendar1.getTimeInMillis();
            int dias = (int) (diferencia / (1000 * 60 * 60 * 24));
            JOptionPane.showMessageDialog(this, dias);
            modeloTabla.setValueAt(jDateFechaIngreso, 0, 0);
            modeloTabla.setValueAt(jDateFechaEgreso, 0, 1);
            modeloTabla.setValueAt(jLTemporada, 0, 2);
            modeloTabla.setValueAt(jComboCiudadOrigen.getSelectedItem(), 0, 3);
            modeloTabla.setValueAt(jComboCiudadDestino.getSelectedItem(), 0, 4);
            modeloTabla.setValueAt(jComboTipoTransporte.getSelectedItem(), 0, 5);
            modeloTabla.setValueAt(jComboTipoAlojamiento.getSelectedItem(), 0, 6);
            modeloTabla.setValueAt(jSCantPasajeros, 0, 7);
            int cantPasajero = (Integer) jSCantPasajeros.getValue();
            // Alojamiento alojamiento=jComboAlojamiento.getSelectedItem();
            double importeDiario = 15000;//alojamiento.getImporteDiario();
            Pasaje pasaje = new Pasaje();
            Double importeTransporte = pasaje.getImporte();
            double imporPresup = importeDiario + importeTransporte * dias * cantPasajero;
            modeloTabla.setValueAt(imporPresup, 0, 7);

        }catch(NullPointerException ex){
            if (jDateFechaIngreso.getDate()==null){
                JOptionPane.showMessageDialog(this,"Debe ingresar la fecha de Ingreso");}
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotonPresupuestoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonModificar;
    private javax.swing.JButton jBotonPresupuesto;
    private javax.swing.JComboBox<Alojamiento> jComboAlojamiento;
    private javax.swing.JComboBox<Ciudad> jComboCiudadDestino;
    private javax.swing.JComboBox<Ciudad> jComboCiudadOrigen;
    private javax.swing.JComboBox<TipoAloj> jComboTipoAlojamiento;
    private javax.swing.JComboBox<TipoTransporte> jComboTipoTransporte;
    private com.toedter.calendar.JDateChooser jDateFechaEgreso;
    private com.toedter.calendar.JDateChooser jDateFechaIngreso;
    private javax.swing.JLabel jLAlojamiento;
    private javax.swing.JLabel jLCantPasajeros;
    private javax.swing.JLabel jLCiudadOrigen;
    private javax.swing.JLabel jLCiudadOrigen1;
    private javax.swing.JLabel jLFechaIngreso;
    private javax.swing.JLabel jLFechaIngreso1;
    private javax.swing.JLabel jLTemporada;
    private javax.swing.JLabel jLTipoTransporte;
    private javax.swing.JLabel jLTipoTransporte1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSCantPasajeros;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaPresupuesto;
    // End of variables declaration//GEN-END:variables

 private void cargarComboCiudad() {
       List<Ciudad> listaCiudad = ciudadData.obtenerCiudades();
       for (Ciudad ciudades : listaCiudad) {
            jComboCiudadOrigen.addItem(new Ciudad(ciudades.getIdCiudad(), ciudades.getNombre(), ciudades.getProvincia(), ciudades.getPais(), ciudades.isEstado()));
            jComboCiudadDestino.addItem(new Ciudad(ciudades.getIdCiudad(), ciudades.getNombre(), ciudades.getProvincia(), ciudades.getPais(), ciudades.isEstado()));
        }
    }
 
 /*private void cargarComboAlojamiento(Ciudad ciudadDestino){
 List<Alojamiento> listaAlojamiento=alojamientoData.seleccionarAlojamiento(ciudadDestino);
 for(Alojamiento alojamientos:listaAlojamiento){
     jComboAlojamiento.addItem(new Alojamiento(alojamientos.getIdAlojamiento(),alojamiento.getTipoAlojamiento(),alojamiento.getFechaIn(),alojamiento.getFechaOut(),true,alojamiento.getTipoServicio(),alojamiento.getImporteDiario(),alojamiento.getCiudadDest()));
 }       
 }*/

    private void cargarComboTransporte() {
        jComboTipoTransporte.addItem(TipoTransporte.ELIJA);
        jComboTipoTransporte.addItem(TipoTransporte.AVION);
        jComboTipoTransporte.addItem(TipoTransporte.COLECTIVO);
        jComboTipoTransporte.addItem(TipoTransporte.TREN);
        jComboTipoTransporte.addItem(TipoTransporte.TAXI);
    }

    private void cargarComboTipoAlojamiento() {
        jComboTipoAlojamiento.addItem(TipoAloj.ELIJA);
        jComboTipoAlojamiento.addItem(TipoAloj.HOTEL);
        jComboTipoAlojamiento.addItem(TipoAloj.HOSTEL);
        jComboTipoAlojamiento.addItem(TipoAloj.HOSTERIA);
        jComboTipoAlojamiento.addItem(TipoAloj.DEPARTAMENTO);
        jComboTipoAlojamiento.addItem(TipoAloj.CABAÑA);
        jComboTipoAlojamiento.addItem(TipoAloj.BUNGALOWS);
         }

    private void armarCabeceraTabla() {
        modeloTabla.addColumn("Fecha de Ingreso");
        modeloTabla.addColumn("Fecha de Salida");
        modeloTabla.addColumn("Temporada");
        modeloTabla.addColumn("Ciudad Origen");
        modeloTabla.addColumn("Ciudad Destino");
        modeloTabla.addColumn("Tipo de Transporte");
        modeloTabla.addColumn("Tipo de ALojamiento");
        modeloTabla.addColumn("Cant. Pasajeros");
        modeloTabla.addColumn("Importe $");

        jTablaPresupuesto.setModel(modeloTabla);
    }

}
