package Vistas;

import Popups.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import AccesoADatos.*;
import Entidades.*;
import com.sun.glass.events.KeyEvent;
import com.sun.glass.events.MouseEvent;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Susana
 */
public class VentanaPasaje extends javax.swing.JInternalFrame {

    private Pasaje_Data pasajeData = new Pasaje_Data();
    private Pasaje pasaje = null;
    private Ciudad ciudad = new Ciudad();
    private Ciudad_Data ciudadData = new Ciudad_Data();
    private Alojamiento_Data alojamientoData = new Alojamiento_Data();
    private Alojamiento alojamiento = null;
    public String idPopUP;

    /**
     * Creates new form VentanaPasaje
     */
    public VentanaPasaje() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana
        cargarComboTipoTransporte();
        desactivarCampos();
        jTIdPasaje.setEnabled(true);
        jBotonModificar.setEnabled(false);
        jBotonEliminar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaPasajes = new javax.swing.JPopupMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLIdPasaje = new javax.swing.JLabel();
        jTIdPasaje = new javax.swing.JTextField();
        jBotonBuscar = new javax.swing.JButton();
        jLTipoTrans = new javax.swing.JLabel();
        jLImporte = new javax.swing.JLabel();
        jTImporte = new javax.swing.JTextField();
        jBotonNuevo = new javax.swing.JButton();
        jBotonGuardar = new javax.swing.JButton();
        jBotonEliminar = new javax.swing.JButton();
        jBotonModificar = new javax.swing.JButton();
        jTCiudadDestino = new javax.swing.JTextField();
        jComboTipoTrans = new javax.swing.JComboBox<>();
        jLCiudadD2 = new javax.swing.JLabel();
        jTCiudadOrigen = new javax.swing.JTextField();
        jLCiudadD3 = new javax.swing.JLabel();
        panelLateral1Ciudad = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelLateral2Ciudad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        closeCiudad = new javax.swing.JButton();
        jTIdCiudadOrigen = new javax.swing.JTextField();
        jTIdCiudadDestino = new javax.swing.JTextField();
        buscarCiudad2 = new javax.swing.JButton();
        buscarPasajes = new javax.swing.JButton();
        buscarCiudad = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLidCO = new javax.swing.JLabel();
        jLidCD = new javax.swing.JLabel();
        jBotonActivar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setTitle("Pasaje");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(800, 600));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(800, 600));

        jLIdPasaje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLIdPasaje.setText("Id Pasaje: ");
        jDesktopPane1.add(jLIdPasaje);
        jLIdPasaje.setBounds(270, 210, 71, 17);

        jTIdPasaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTIdPasaje.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTIdPasaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTIdPasajeKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTIdPasaje);
        jTIdPasaje.setBounds(360, 210, 104, 20);

        jBotonBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonBuscar.setText("Buscar");
        jBotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonBuscar);
        jBotonBuscar.setBounds(680, 180, 90, 31);

        jLTipoTrans.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTipoTrans.setText("Tipo Transporte:");
        jDesktopPane1.add(jLTipoTrans);
        jLTipoTrans.setBounds(310, 380, 115, 17);

        jLImporte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLImporte.setText("Importe Ida y Vuelta: $");
        jDesktopPane1.add(jLImporte);
        jLImporte.setBounds(470, 460, 154, 17);

        jTImporte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTImporteKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTImporte);
        jTImporte.setBounds(640, 460, 104, 23);

        jBotonNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonNuevo.setText("Nuevo");
        jBotonNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonNuevoActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonNuevo);
        jBotonNuevo.setBounds(260, 530, 90, 31);

        jBotonGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonGuardar.setText("Guardar");
        jBotonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonGuardarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonGuardar);
        jBotonGuardar.setBounds(360, 530, 100, 31);

        jBotonEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonEliminar.setText("Eliminar");
        jBotonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEliminarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonEliminar);
        jBotonEliminar.setBounds(590, 530, 100, 31);

        jBotonModificar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonModificar.setText("Modificar");
        jBotonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonModificarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonModificar);
        jBotonModificar.setBounds(470, 530, 110, 31);

        jTCiudadDestino.setEditable(false);
        jTCiudadDestino.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTCiudadDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(jTCiudadDestino);
        jTCiudadDestino.setBounds(370, 330, 320, 23);

        jDesktopPane1.add(jComboTipoTrans);
        jComboTipoTrans.setBounds(450, 370, 200, 26);

        jLCiudadD2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCiudadD2.setText("Ciudad Origen: ");
        jDesktopPane1.add(jLCiudadD2);
        jLCiudadD2.setBounds(250, 290, 109, 17);

        jTCiudadOrigen.setEditable(false);
        jTCiudadOrigen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTCiudadOrigen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(jTCiudadOrigen);
        jTCiudadOrigen.setBounds(370, 290, 320, 23);

        jLCiudadD3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCiudadD3.setText("Ciudad Destino:");
        jDesktopPane1.add(jLCiudadD3);
        jLCiudadD3.setBounds(250, 330, 111, 17);

        panelLateral1Ciudad.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo2.png"))); // NOI18N

        javax.swing.GroupLayout panelLateral1CiudadLayout = new javax.swing.GroupLayout(panelLateral1Ciudad);
        panelLateral1Ciudad.setLayout(panelLateral1CiudadLayout);
        panelLateral1CiudadLayout.setHorizontalGroup(
            panelLateral1CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateral1CiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLateral1CiudadLayout.setVerticalGroup(
            panelLateral1CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateral1CiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(panelLateral1Ciudad);
        panelLateral1Ciudad.setBounds(0, 0, 229, 172);

        panelLateral2Ciudad.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout panelLateral2CiudadLayout = new javax.swing.GroupLayout(panelLateral2Ciudad);
        panelLateral2Ciudad.setLayout(panelLateral2CiudadLayout);
        panelLateral2CiudadLayout.setHorizontalGroup(
            panelLateral2CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        panelLateral2CiudadLayout.setVerticalGroup(
            panelLateral2CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jDesktopPane1.add(panelLateral2Ciudad);
        panelLateral2Ciudad.setBounds(0, 171, 229, 440);

        jLabel1.setFont(new java.awt.Font("Broadway", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pasajes");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(400, 50, 160, 50);

        closeCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flechaAtras.png"))); // NOI18N
        closeCiudad.setText("Atrás");
        closeCiudad.setAlignmentY(0.0F);
        closeCiudad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeCiudad.setBorderPainted(false);
        closeCiudad.setContentAreaFilled(false);
        closeCiudad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCiudadActionPerformed(evt);
            }
        });
        jDesktopPane1.add(closeCiudad);
        closeCiudad.setBounds(670, 20, 90, 38);

        jTIdCiudadOrigen.setBorder(null);
        jTIdCiudadOrigen.setEnabled(false);
        jDesktopPane1.add(jTIdCiudadOrigen);
        jTIdCiudadOrigen.setBounds(256, 420, 0, 0);

        jTIdCiudadDestino.setBorder(null);
        jTIdCiudadDestino.setEnabled(false);
        jDesktopPane1.add(jTIdCiudadDestino);
        jTIdCiudadDestino.setBounds(260, 450, 0, 10);

        buscarCiudad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        buscarCiudad2.setBorderPainted(false);
        buscarCiudad2.setContentAreaFilled(false);
        buscarCiudad2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarCiudad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCiudad2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(buscarCiudad2);
        buscarCiudad2.setBounds(700, 330, 30, 30);

        buscarPasajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        buscarPasajes.setBorderPainted(false);
        buscarPasajes.setContentAreaFilled(false);
        buscarPasajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarPasajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPasajesActionPerformed(evt);
            }
        });
        jDesktopPane1.add(buscarPasajes);
        buscarPasajes.setBounds(470, 200, 30, 30);

        buscarCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        buscarCiudad.setBorderPainted(false);
        buscarCiudad.setContentAreaFilled(false);
        buscarCiudad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCiudadActionPerformed(evt);
            }
        });
        jDesktopPane1.add(buscarCiudad);
        buscarCiudad.setBounds(700, 290, 30, 30);

        clearButton.setText("Limpiar");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jDesktopPane1.add(clearButton);
        clearButton.setBounds(680, 220, 90, 32);

        jLidCO.setBackground(new java.awt.Color(255, 255, 255));
        jLidCO.setForeground(new java.awt.Color(255, 255, 255));
        jLidCO.setEnabled(false);
        jDesktopPane1.add(jLidCO);
        jLidCO.setBounds(260, 290, 0, 0);

        jLidCD.setBackground(new java.awt.Color(255, 255, 255));
        jLidCD.setForeground(new java.awt.Color(255, 255, 255));
        jLidCD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLidCD.setEnabled(false);
        jDesktopPane1.add(jLidCD);
        jLidCD.setBounds(260, 330, 0, 0);

        jBotonActivar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonActivar.setText("Activar");
        jBotonActivar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonActivarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonActivar);
        jBotonActivar.setBounds(700, 530, 90, 31);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarActionPerformed
        try {
            jBotonGuardar.setEnabled(false);

            Pasaje pasaje = new Pasaje();
            int id = Integer.parseInt(jTIdPasaje.getText());
            String obtenerTipoTransporte;
            pasaje = pasajeData.buscarPasaje(id);
            if (pasaje != null) {
                obtenerTipoTransporte = pasaje.getTipoTransporte();
                Ciudad cO, cD;
                cO = ciudadData.buscarCiudad(pasaje.getNombreCiudadO().getIdCiudad());
                cD = ciudadData.buscarCiudad(pasaje.getNombreCiudadD().getIdCiudad());
                jLidCO.setText(pasaje.getNombreCiudadO().getIdCiudad() + "");
                jTCiudadOrigen.setText(cO.getPais().toUpperCase() + " - " + cO.getProvincia() + ", " + cO.getNombre());
                jLidCD.setText(pasaje.getNombreCiudadD().getIdCiudad() + "");
                jTCiudadDestino.setText(cD.getPais().toUpperCase() + " - " + cD.getProvincia() + ", " + cD.getNombre());
                jTImporte.setText(pasaje.getImporte() + "");
                jComboTipoTrans.getModel().setSelectedItem(pasaje.getTipoTransporte());
                activarCampos();
                jBotonModificar.setEnabled(true);
                jBotonEliminar.setEnabled(true);
                buscarCiudad.setEnabled(true);
                buscarCiudad2.setEnabled(true);
            }
        } catch (NumberFormatException es) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID valido: " + es);
            limpiarCampos();
            jTIdPasaje.setEnabled(true);
        }
    }//GEN-LAST:event_jBotonBuscarActionPerformed

    private void jBotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonNuevoActionPerformed
        activarCampos();
        limpiarCampos();
        pasaje = null;
        jTIdPasaje.setEnabled(false);
        buscarPasajes.setEnabled(false);
        jBotonNuevo.setEnabled(true);
        jBotonGuardar.setEnabled(true);
        jBotonEliminar.setEnabled(false);
        jBotonModificar.setEnabled(false);
        buscarCiudad.setEnabled(true);
        buscarCiudad2.setEnabled(true);
    }//GEN-LAST:event_jBotonNuevoActionPerformed

    private void jBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonGuardarActionPerformed
        Pasaje pasaje = null; //
        //pongo todos los valores del formulario en variables
        Integer idCO, idCD;
        Ciudad cO, cD;
        idCO = Integer.parseInt(jLidCO.getText());
        cO = ciudadData.buscarCiudad(idCO);
        idCD = Integer.parseInt(jLidCD.getText());
        cD = ciudadData.buscarCiudad(idCD);
        TipoTransporte tipoTrans = (TipoTransporte) jComboTipoTrans.getSelectedItem();
        String tipoT = tipoTrans.name();//parseo tipo tipoAlojamiento a String 
        Boolean estado = true;
        double importe = Double.parseDouble(jTImporte.getText());
        if (pasaje == null) {//instancio pasaje con las variables y guardo en la base de datos
            pasaje = new Pasaje(tipoT, importe, cO, cD, estado);
            pasajeData.guardarPasaje(pasaje);
            jBotonNuevo.setSelected(false);
            desactivarCampos();
            limpiarCampos();
            jTIdPasaje.setEnabled(true);
            buscarPasajes.setEnabled(true);
            jTIdPasaje.setText("");
        }


    }//GEN-LAST:event_jBotonGuardarActionPerformed

    private void jBotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEliminarActionPerformed
//        int id = Integer.parseInt(jTIdPasaje.getText());
//        String TipoTransporte = (String) jComboTipoTrans.getSelectedItem();
//        Double importe = Double.parseDouble(jTImporte.getText());
//        int idCiudadD = Integer.parseInt(jLidCD.getText());
//        Ciudad ciuD = ciudadData.buscarCiudad(idCiudadD);
//        int idCiudadO = Integer.parseInt(jLidCO.getText());
//        Ciudad ciuO = ciudadData.buscarCiudad(idCiudadO);
//        if (pasaje == null) {
//            pasaje = new Pasaje(TipoTransporte, importe, ciuO, ciuD, false);
//            int respuesta = JOptionPane.showConfirmDialog(null, "Esta por borrar un Pasaje ¿Quieres continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);
//            if (respuesta == JOptionPane.YES_OPTION) {
//                pasajeData.eliminarPasaje(id);;
//                limpiarCampos();
//                activarCampos();
//                jTIdPasaje.requestFocus();
//            }
//        }
        int respuesta = JOptionPane.showConfirmDialog(null, "Esta por borrar un Pasaje ¿Quieres continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            Pasaje_Data borrar = new Pasaje_Data();
            borrar.eliminarPasaje(Integer.parseInt(jTIdPasaje.getText()));
            limpiarCampos();
            desactivarCampos();
            jTIdPasaje.requestFocus();
        }
    }//GEN-LAST:event_jBotonEliminarActionPerformed

    private void jBotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonModificarActionPerformed
        Pasaje pasaje = new Pasaje();
        try {
            Integer id = Integer.parseInt(jTIdPasaje.getText());
            Integer idCO, idCD;
            idCO = Integer.parseInt(jLidCO.getText());
            idCD = Integer.parseInt(jLidCD.getText());
//            TipoTransporte tTrans = (TipoTransporte) jComboTipoTrans.getSelectedItem();
            if (jComboTipoTrans.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Rellene todas las celdas para continuar");
            } else {
                String transporte = jComboTipoTrans.getSelectedItem().toString();
                Boolean estado = true;
                double importe = Double.parseDouble(jTImporte.getText());
                Ciudad cO, cD;
                cO = ciudadData.buscarCiudad(idCO);
                cD = ciudadData.buscarCiudad(idCD);
                Pasaje pasaj = pasajeData.buscarPasaje(id);
                if (id == pasaj.getIdPasajero()) {
                    pasaj.setIdPasajero(id);
                    pasaj.setEstado(estado);
                    pasaj.setImporte(importe);
                    pasaj.setTipoTransporte(transporte);
                    pasaj.setNombreCiudadO(cO);
                    pasaj.setNombreCiudadD(cD);
                    pasajeData.modificarPasaje(pasaj);
                }
            }
            jBotonNuevo.setEnabled(true);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "error" + ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBotonModificarActionPerformed

    private void closeCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCiudadActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeCiudadActionPerformed

    private void buscarPasajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPasajesActionPerformed
        jDesktopPane1.repaint();
        popupPasajes popupPasajes = new popupPasajes();
        popupPasajes.setVisible(true);
        jDesktopPane1.add(popupPasajes);
        jDesktopPane1.moveToFront(popupPasajes);
    }//GEN-LAST:event_buscarPasajesActionPerformed

    private void buscarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCiudadActionPerformed
        jDesktopPane1.repaint();
        popupPasajesCity popupPasajesCity = new popupPasajesCity();
        popupPasajesCity.setVisible(true);
        jDesktopPane1.add(popupPasajesCity);
        jDesktopPane1.moveToFront(popupPasajesCity);
    }//GEN-LAST:event_buscarCiudadActionPerformed

    private void buscarCiudad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCiudad2ActionPerformed
        jDesktopPane1.repaint();
        popupPasajesCityD popupPasajesCityD = new popupPasajesCityD();
        popupPasajesCityD.setVisible(true);
        jDesktopPane1.add(popupPasajesCityD);
        jDesktopPane1.moveToFront(popupPasajesCityD);
    }//GEN-LAST:event_buscarCiudad2ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        desactivarCampos();
        limpiarCampos();
        jTIdPasaje.setEnabled(true);
        jTIdPasaje.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jTIdPasajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTIdPasajeKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTIdPasajeKeyTyped

    private void jTImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTImporteKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter != KeyEvent.VK_BACKSPACE) && (caracter != KeyEvent.VK_PERIOD)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTImporteKeyTyped

    private void jBotonActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonActivarActionPerformed
        //        ciudadData.ActivarCiudad();
        //        JOptionPane.showMessageDialog(this, "Todas las ciudades estan activas");
        jDesktopPane1.repaint();
        popupPasajesActivar popupPasajesActivar = new popupPasajesActivar();
        popupPasajesActivar.setVisible(true);
        jDesktopPane1.add(popupPasajesActivar);
        jDesktopPane1.moveToFront(popupPasajesActivar);
    }//GEN-LAST:event_jBotonActivarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCiudad;
    private javax.swing.JButton buscarCiudad2;
    private javax.swing.JButton buscarPasajes;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeCiudad;
    private javax.swing.JButton jBotonActivar;
    private javax.swing.JButton jBotonBuscar;
    private javax.swing.JButton jBotonEliminar;
    private javax.swing.JButton jBotonGuardar;
    private javax.swing.JButton jBotonModificar;
    private javax.swing.JButton jBotonNuevo;
    private javax.swing.JComboBox<TipoTransporte> jComboTipoTrans;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLCiudadD2;
    private javax.swing.JLabel jLCiudadD3;
    private javax.swing.JLabel jLIdPasaje;
    private javax.swing.JLabel jLImporte;
    private javax.swing.JLabel jLTipoTrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLidCD;
    public static javax.swing.JLabel jLidCO;
    public static javax.swing.JTextField jTCiudadDestino;
    public static javax.swing.JTextField jTCiudadOrigen;
    private javax.swing.JTextField jTIdCiudadDestino;
    private javax.swing.JTextField jTIdCiudadOrigen;
    public static javax.swing.JTextField jTIdPasaje;
    private javax.swing.JTextField jTImporte;
    private javax.swing.JPopupMenu listaPasajes;
    private javax.swing.JPanel panelLateral1Ciudad;
    private javax.swing.JPanel panelLateral2Ciudad;
    // End of variables declaration//GEN-END:variables

    private void cargarComboTipoTransporte() {

        jComboTipoTrans.addItem(TipoTransporte.ELIJA);
        jComboTipoTrans.addItem(TipoTransporte.AVION);
        jComboTipoTrans.addItem(TipoTransporte.COLECTIVO);
        jComboTipoTrans.addItem(TipoTransporte.TREN);
        jComboTipoTrans.addItem(TipoTransporte.TAXI);

    }

    public void desactivarCampos() {
        buscarCiudad.setEnabled(false);
        buscarCiudad2.setEnabled(false);
        jTIdPasaje.setEnabled(false);
        jTImporte.setEnabled(false);
        jTCiudadDestino.setEnabled(false);
        jTIdCiudadOrigen.setEnabled(false);
        jTCiudadOrigen.setEnabled(false);
        jTIdCiudadDestino.setEnabled(false);
        jComboTipoTrans.setEnabled(false);
        jBotonEliminar.setEnabled(false);
        jBotonModificar.setEnabled(false);
        jBotonGuardar.setEnabled(false);
    }

    public void activarCampos() {
        jTIdPasaje.setEnabled(true);
        jTImporte.setEnabled(true);
        jTCiudadDestino.setEnabled(true);
        jTIdCiudadOrigen.setEnabled(true);
        jTCiudadOrigen.setEnabled(true);
        jTIdCiudadDestino.setEnabled(true);
        jComboTipoTrans.setEnabled(true);
        jBotonEliminar.setEnabled(true);
        jBotonModificar.setEnabled(true);

    }

    public void limpiarCampos() {
        jTIdPasaje.setText("");
        jLidCO.setText("");
        jLidCD.setText("");
        jTImporte.setText("");
        jComboTipoTrans.setSelectedIndex(0);
        jTCiudadDestino.setText("");
        jTIdCiudadDestino.setText("");
        jTCiudadOrigen.setText("");
        jTIdCiudadOrigen.setText("");
    }

}
