package Vistas;

import Popups.popupPresupuestosCO;
import Popups.popupPresupuestosP;
import Popups.popupPresupuestosCD;
import Popups.popupPresupuestosA;
import javax.swing.table.DefaultTableModel;
import AccesoADatos.*;
import Entidades.*;
import com.sun.glass.events.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Susana
 */
public class VentanaPresupuesto extends javax.swing.JInternalFrame {

//    private DefaultTableModel modeloTabla = new DefaultTableModel();
//    private Ciudad_Data ciudadData = new Ciudad_Data();
    public static Ciudad ciudadOrigenPaquete = new Ciudad();
    public static Ciudad ciudadDestinoPaquete = new Ciudad();
    public static Alojamiento alojamientoPaquete = new Alojamiento();
    public static Pasaje pasajePaquete = new Pasaje();
//    private Alojamiento_Data alojamientoData = new Alojamiento_Data();

    /**
     * Creates new form VentanaPresupuesto
     */
    public VentanaPresupuesto() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana
        bloquearCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelLateral2Ciudad = new javax.swing.JPanel();
        panelLateral1Ciudad = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTCiudadD = new javax.swing.JLabel();
        jTAlojamiento = new javax.swing.JLabel();
        jTCiudadO = new javax.swing.JLabel();
        jTFCD = new javax.swing.JTextField();
        jTFCO = new javax.swing.JTextField();
        jBA = new javax.swing.JButton();
        jBCO = new javax.swing.JButton();
        jBCD = new javax.swing.JButton();
        idCO = new javax.swing.JLabel();
        idCD = new javax.swing.JLabel();
        jBP = new javax.swing.JButton();
        jTFTP = new javax.swing.JTextField();
        jTPasaje = new javax.swing.JLabel();
        jTFIP = new javax.swing.JTextField();
        jTImPasaje = new javax.swing.JLabel();
        jTFCantidadPasajeros = new javax.swing.JTextField();
        jLCantidadPasajeros = new javax.swing.JLabel();
        jTFAl2 = new javax.swing.JTextField();
        jTAl2 = new javax.swing.JLabel();
        jTFAl1 = new javax.swing.JTextField();
        jTAl1 = new javax.swing.JLabel();
        jTAl3 = new javax.swing.JLabel();
        jTFAl3 = new javax.swing.JTextField();
        jTPasaje2 = new javax.swing.JLabel();
        jTCheckIN = new javax.swing.JLabel();
        checkOUT = new com.toedter.calendar.JDateChooser();
        checkIN = new com.toedter.calendar.JDateChooser();
        jLAclaracion1 = new javax.swing.JLabel();
        temporada1 = new javax.swing.JLabel();
        temporada1.setVisible(false);
        jTPasaje4 = new javax.swing.JLabel();
        jTPasaje5 = new javax.swing.JLabel();
        jTPasaje6 = new javax.swing.JLabel();
        jTPasaje7 = new javax.swing.JLabel();
        jTPasaje8 = new javax.swing.JLabel();
        precioPasajeT = new javax.swing.JTextField();
        jTPasaje9 = new javax.swing.JLabel();
        jTPasaje10 = new javax.swing.JLabel();
        precioTotal = new javax.swing.JTextField();
        jBotonCalcular = new javax.swing.JButton();
        jBotonConfirmar = new javax.swing.JButton();
        jTPasaje1 = new javax.swing.JLabel();
        temporada2 = new javax.swing.JLabel();
        temporada2.setVisible(false);
        temporada3 = new javax.swing.JLabel();
        temporada3.setVisible(false);
        jTCheckOUT1 = new javax.swing.JLabel();
        precioAlojT = new javax.swing.JTextField();
        jBotonLimpiar = new javax.swing.JButton();
        jLTipoTemporada = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setTitle("Presupuesto");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(800, 600));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(800, 600));

        panelLateral2Ciudad.setBackground(new java.awt.Color(255, 204, 51));
        panelLateral2Ciudad.setPreferredSize(new java.awt.Dimension(229, 410));

        javax.swing.GroupLayout panelLateral2CiudadLayout = new javax.swing.GroupLayout(panelLateral2Ciudad);
        panelLateral2Ciudad.setLayout(panelLateral2CiudadLayout);
        panelLateral2CiudadLayout.setHorizontalGroup(
            panelLateral2CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        panelLateral2CiudadLayout.setVerticalGroup(
            panelLateral2CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jDesktopPane1.add(panelLateral2Ciudad);
        panelLateral2Ciudad.setBounds(0, 171, 229, 450);

        panelLateral1Ciudad.setBackground(new java.awt.Color(255, 255, 255));
        panelLateral1Ciudad.setMinimumSize(new java.awt.Dimension(229, 180));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo2.png"))); // NOI18N

        javax.swing.GroupLayout panelLateral1CiudadLayout = new javax.swing.GroupLayout(panelLateral1Ciudad);
        panelLateral1Ciudad.setLayout(panelLateral1CiudadLayout);
        panelLateral1CiudadLayout.setHorizontalGroup(
            panelLateral1CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLateral1CiudadLayout.setVerticalGroup(
            panelLateral1CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateral1CiudadLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.add(panelLateral1Ciudad);
        panelLateral1Ciudad.setBounds(0, 0, 229, 180);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flechaAtras.png"))); // NOI18N
        close.setText("Atrás");
        close.setAlignmentY(0.0F);
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jDesktopPane1.add(close);
        close.setBounds(670, 20, 90, 38);

        jLabel1.setFont(new java.awt.Font("Broadway", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRESUPUESTO");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(370, 50, 220, 50);

        jTCiudadD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTCiudadD.setText("Destino:");
        jDesktopPane1.add(jTCiudadD);
        jTCiudadD.setBounds(240, 210, 80, 17);

        jTAlojamiento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTAlojamiento.setText("Alojamiento:");
        jDesktopPane1.add(jTAlojamiento);
        jTAlojamiento.setBounds(240, 290, 100, 17);

        jTCiudadO.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTCiudadO.setText("Origen:");
        jDesktopPane1.add(jTCiudadO);
        jTCiudadO.setBounds(240, 180, 80, 17);

        jTFCD.setEditable(false);
        jTFCD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(jTFCD);
        jTFCD.setBounds(320, 210, 390, 24);

        jTFCO.setEditable(false);
        jTFCO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(jTFCO);
        jTFCO.setBounds(320, 180, 390, 24);

        jBA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        jBA.setBorderPainted(false);
        jBA.setContentAreaFilled(false);
        jBA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBA);
        jBA.setBounds(320, 280, 62, 40);

        jBCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        jBCO.setBorderPainted(false);
        jBCO.setContentAreaFilled(false);
        jBCO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCOActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBCO);
        jBCO.setBounds(710, 170, 62, 40);

        jBCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        jBCD.setBorderPainted(false);
        jBCD.setContentAreaFilled(false);
        jBCD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCDActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBCD);
        jBCD.setBounds(710, 210, 62, 40);

        idCO.setBackground(new java.awt.Color(255, 255, 255));
        idCO.setForeground(new java.awt.Color(255, 255, 255));
        idCO.setEnabled(false);
        jDesktopPane1.add(idCO);
        idCO.setBounds(0, 0, 0, 0);

        idCD.setBackground(new java.awt.Color(255, 255, 255));
        idCD.setForeground(new java.awt.Color(255, 255, 255));
        idCD.setEnabled(false);
        jDesktopPane1.add(idCD);
        idCD.setBounds(0, 0, 0, 0);

        jBP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        jBP.setBorderPainted(false);
        jBP.setContentAreaFilled(false);
        jBP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBP);
        jBP.setBounds(290, 240, 62, 40);

        jTFTP.setEditable(false);
        jTFTP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(jTFTP);
        jTFTP.setBounds(390, 250, 120, 24);

        jTPasaje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTPasaje.setText("Pasaje:");
        jDesktopPane1.add(jTPasaje);
        jTPasaje.setBounds(240, 250, 100, 17);

        jTFIP.setEditable(false);
        jTFIP.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTFIP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(jTFIP);
        jTFIP.setBounds(620, 250, 90, 24);

        jTImPasaje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTImPasaje.setText("Importe: $");
        jDesktopPane1.add(jTImPasaje);
        jTImPasaje.setBounds(550, 250, 100, 17);

        jTFCantidadPasajeros.setEditable(false);
        jTFCantidadPasajeros.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTFCantidadPasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTFCantidadPasajeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCantidadPasajerosKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTFCantidadPasajeros);
        jTFCantidadPasajeros.setBounds(460, 440, 70, 24);

        jLCantidadPasajeros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCantidadPasajeros.setText("Elija la cantidad de pasajeros:");
        jDesktopPane1.add(jLCantidadPasajeros);
        jLCantidadPasajeros.setBounds(240, 440, 240, 17);

        jTFAl2.setEditable(false);
        jTFAl2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(jTFAl2);
        jTFAl2.setBounds(350, 330, 190, 24);

        jTAl2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTAl2.setText("Tipo Servicio:");
        jDesktopPane1.add(jTAl2);
        jTAl2.setBounds(240, 330, 120, 17);

        jTFAl1.setEditable(false);
        jTFAl1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(jTFAl1);
        jTFAl1.setBounds(560, 290, 130, 24);

        jTAl1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTAl1.setText("Tipo Alojamiento:");
        jDesktopPane1.add(jTAl1);
        jTAl1.setBounds(430, 290, 160, 17);

        jTAl3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTAl3.setText("Importe: $");
        jDesktopPane1.add(jTAl3);
        jTAl3.setBounds(550, 330, 100, 17);

        jTFAl3.setEditable(false);
        jTFAl3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTFAl3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(jTFAl3);
        jTFAl3.setBounds(620, 330, 90, 24);

        jTPasaje2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTPasaje2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTPasaje2.setText("$");
        jDesktopPane1.add(jTPasaje2);
        jTPasaje2.setBounds(530, 490, 30, 17);

        jTCheckIN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTCheckIN.setText("Seleccionar fecha de CheckIn:");
        jDesktopPane1.add(jTCheckIN);
        jTCheckIN.setBounds(240, 370, 230, 17);

        checkOUT.setEnabled(false);
        jDesktopPane1.add(checkOUT);
        checkOUT.setBounds(480, 400, 150, 29);

        checkIN.setEnabled(false);
        jDesktopPane1.add(checkIN);
        checkIN.setBounds(480, 370, 150, 29);

        jLAclaracion1.setForeground(new java.awt.Color(204, 0, 0));
        jLAclaracion1.setText("Precio por día.");
        jDesktopPane1.add(jLAclaracion1);
        jLAclaracion1.setBounds(640, 350, 90, 16);

        temporada1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        temporada1.setForeground(new java.awt.Color(0, 102, 0));
        temporada1.setText("Temporada ALTA");
        jDesktopPane1.add(temporada1);
        temporada1.setBounds(550, 430, 160, 22);

        jTPasaje4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTPasaje4.setText("Pasajes");
        jDesktopPane1.add(jTPasaje4);
        jTPasaje4.setBounds(350, 510, 120, 17);

        jTPasaje5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTPasaje5.setMaximumSize(new java.awt.Dimension(29, 17));
        jTPasaje5.setMinimumSize(new java.awt.Dimension(29, 17));
        jTPasaje5.setPreferredSize(new java.awt.Dimension(29, 17));
        jDesktopPane1.add(jTPasaje5);
        jTPasaje5.setBounds(470, 490, 29, 17);

        jTPasaje6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTPasaje6.setText("días");
        jDesktopPane1.add(jTPasaje6);
        jTPasaje6.setBounds(490, 490, 40, 17);

        jTPasaje7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTPasaje7.setText("Alojamiento por");
        jDesktopPane1.add(jTPasaje7);
        jTPasaje7.setBounds(350, 490, 120, 17);

        jTPasaje8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTPasaje8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTPasaje8.setText("$");
        jDesktopPane1.add(jTPasaje8);
        jTPasaje8.setBounds(530, 510, 30, 17);

        precioPasajeT.setEditable(false);
        precioPasajeT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        precioPasajeT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(precioPasajeT);
        precioPasajeT.setBounds(560, 510, 90, 24);

        jTPasaje9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTPasaje9.setText("Total");
        jDesktopPane1.add(jTPasaje9);
        jTPasaje9.setBounds(350, 550, 120, 17);

        jTPasaje10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTPasaje10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTPasaje10.setText("$");
        jDesktopPane1.add(jTPasaje10);
        jTPasaje10.setBounds(530, 550, 30, 17);

        precioTotal.setEditable(false);
        precioTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        precioTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(precioTotal);
        precioTotal.setBounds(560, 550, 90, 24);

        jBotonCalcular.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonCalcular.setText("Calcular");
        jBotonCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCalcularActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonCalcular);
        jBotonCalcular.setBounds(670, 380, 90, 31);

        jBotonConfirmar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonConfirmar.setText("Confirmar");
        jBotonConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonConfirmarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonConfirmar);
        jBotonConfirmar.setBounds(670, 500, 100, 31);

        jTPasaje1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTPasaje1.setText("Precio total Presupuesto por persona");
        jDesktopPane1.add(jTPasaje1);
        jTPasaje1.setBounds(330, 470, 370, 22);

        temporada2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        temporada2.setForeground(new java.awt.Color(0, 0, 204));
        temporada2.setText("Temporada MEDIA");
        jDesktopPane1.add(temporada2);
        temporada2.setBounds(560, 430, 180, 17);

        temporada3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        temporada3.setForeground(new java.awt.Color(153, 153, 153));
        temporada3.setText("Temporada BAJA");
        jDesktopPane1.add(temporada3);
        temporada3.setBounds(560, 430, 160, 22);

        jTCheckOUT1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTCheckOUT1.setText("Seleccionar fecha de CheckOut:");
        jDesktopPane1.add(jTCheckOUT1);
        jTCheckOUT1.setBounds(240, 400, 240, 17);

        precioAlojT.setEditable(false);
        precioAlojT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        precioAlojT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.add(precioAlojT);
        precioAlojT.setBounds(560, 490, 90, 24);

        jBotonLimpiar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonLimpiar.setText("Limpiar");
        jBotonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonLimpiar);
        jBotonLimpiar.setBounds(670, 530, 100, 31);

        jLTipoTemporada.setBackground(new java.awt.Color(255, 255, 255));
        jLTipoTemporada.setForeground(new java.awt.Color(255, 255, 255));
        jLTipoTemporada.setText("jLabel2");
        jLTipoTemporada.setEnabled(false);
        jLTipoTemporada.setMaximumSize(new java.awt.Dimension(0, 0));
        jLTipoTemporada.setMinimumSize(new java.awt.Dimension(0, 0));
        jLTipoTemporada.setPreferredSize(new java.awt.Dimension(0, 0));
        jDesktopPane1.add(jLTipoTemporada);
        jLTipoTemporada.setBounds(0, 0, 0, 0);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void jBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAActionPerformed
        jDesktopPane1.repaint();
        popupPresupuestosA popupPresupuestosA = new popupPresupuestosA();
        popupPresupuestosA.setVisible(true);
        jDesktopPane1.add(popupPresupuestosA);
        jDesktopPane1.moveToFront(popupPresupuestosA);
    }//GEN-LAST:event_jBAActionPerformed

    private void jBCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCOActionPerformed
        jDesktopPane1.repaint();
        popupPresupuestosCO popupPresupuestosCO = new popupPresupuestosCO();
        popupPresupuestosCO.setVisible(true);
        jDesktopPane1.add(popupPresupuestosCO);
        jDesktopPane1.moveToFront(popupPresupuestosCO);
    }//GEN-LAST:event_jBCOActionPerformed

    private void jBCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCDActionPerformed
        jDesktopPane1.repaint();
        popupPresupuestosCD popupPresupuestosCD = new popupPresupuestosCD();
        popupPresupuestosCD.setVisible(true);
        jDesktopPane1.add(popupPresupuestosCD);
        jDesktopPane1.moveToFront(popupPresupuestosCD);
    }//GEN-LAST:event_jBCDActionPerformed

    private void jBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPActionPerformed
        jDesktopPane1.repaint();
        popupPresupuestosP popupPresupuestosP = new popupPresupuestosP();
        popupPresupuestosP.setVisible(true);
        jDesktopPane1.add(popupPresupuestosP);
        jDesktopPane1.moveToFront(popupPresupuestosP);
    }//GEN-LAST:event_jBPActionPerformed

    private void jBotonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCalcularActionPerformed
        try {
            temporada1.setVisible(false);
            temporada2.setVisible(false);
            temporada3.setVisible(false);
            long difference_In_Time = checkOUT.getDate().getTime() - checkIN.getDate().getTime();
            long difference_In_Days = (difference_In_Time / (1000 * 60 * 60 * 24)) % 365;
            jTPasaje5.setText(difference_In_Days + "");
            precioAlojT.setText(calcularTemporada(difference_In_Days * Double.parseDouble(jTFAl3.getText()), checkIN.getDate()) + "");
            precioPasajeT.setText(calcularTemporada(Double.parseDouble(jTFIP.getText()), checkIN.getDate()).toString());
            Double total = Double.parseDouble(precioAlojT.getText()) + Double.parseDouble(precioPasajeT.getText());
            //total = calcularTemporada(total, checkIN.getDate());
            precioTotal.setText(total * Integer.parseInt(jTFCantidadPasajeros.getText()) + "");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos para calcular");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la cantidad de pasajeros para continuar");
            precioAlojT.setText("");
            precioPasajeT.setText("");
            temporada1.setVisible(false);
            temporada2.setVisible(false);
            temporada3.setVisible(false);
        }
    }//GEN-LAST:event_jBotonCalcularActionPerformed

    private void jBotonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonConfirmarActionPerformed
        Paquete_Data p1 = new Paquete_Data();
        Paquete p2 = new Paquete();
        p2.setOrigen(ciudadOrigenPaquete);
        p2.setDestino(ciudadDestinoPaquete);
        p2.setPasaje(pasajePaquete);
        alojamientoPaquete.setFechaIn(checkIN.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        alojamientoPaquete.setFechaOut(checkOUT.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        Alojamiento_Data guardarAlojamientoPaquete = new Alojamiento_Data();
        guardarAlojamientoPaquete.guardarAlojamiento(alojamientoPaquete);
        p2.setAlojamiento(alojamientoPaquete);
        p2.setnPersonas(Integer.parseInt(jTFCantidadPasajeros.getText()));
        p2.setTipoTemporada(jLTipoTemporada.getText());
        p2.setPrecio(Double.parseDouble(precioTotal.getText()));
        p2.isEstado(true);
        p1.guardarPaquete(p2);
    }//GEN-LAST:event_jBotonConfirmarActionPerformed

    private void jTFCantidadPasajerosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCantidadPasajerosKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFCantidadPasajerosKeyTyped

    private void jBotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLimpiarActionPerformed
        bloquearCampos();
        limpiarCampos();
        precioAlojT.setText("");
        precioPasajeT.setText("");
        precioTotal.setText("");
        jTFCO.setText("");
        checkIN.setCalendar(null);
        checkOUT.setCalendar(null);
        
    }//GEN-LAST:event_jBotonLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser checkIN;
    public static com.toedter.calendar.JDateChooser checkOUT;
    private javax.swing.JButton close;
    public static javax.swing.JLabel idCD;
    public static javax.swing.JLabel idCO;
    public static javax.swing.JButton jBA;
    public static javax.swing.JButton jBCD;
    private javax.swing.JButton jBCO;
    public static javax.swing.JButton jBP;
    private javax.swing.JButton jBotonCalcular;
    private javax.swing.JButton jBotonConfirmar;
    private javax.swing.JButton jBotonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    public static javax.swing.JLabel jLAclaracion1;
    private javax.swing.JLabel jLCantidadPasajeros;
    private static javax.swing.JLabel jLTipoTemporada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jTAl1;
    private javax.swing.JLabel jTAl2;
    private javax.swing.JLabel jTAl3;
    private javax.swing.JLabel jTAlojamiento;
    private javax.swing.JLabel jTCheckIN;
    private javax.swing.JLabel jTCheckOUT1;
    private javax.swing.JLabel jTCiudadD;
    private javax.swing.JLabel jTCiudadO;
    public static javax.swing.JTextField jTFAl1;
    public static javax.swing.JTextField jTFAl2;
    public static javax.swing.JTextField jTFAl3;
    public static javax.swing.JTextField jTFCD;
    public static javax.swing.JTextField jTFCO;
    public static javax.swing.JTextField jTFCantidadPasajeros;
    public static javax.swing.JTextField jTFIP;
    public static javax.swing.JTextField jTFTP;
    private javax.swing.JLabel jTImPasaje;
    private javax.swing.JLabel jTPasaje;
    private javax.swing.JLabel jTPasaje1;
    private javax.swing.JLabel jTPasaje10;
    private javax.swing.JLabel jTPasaje2;
    private javax.swing.JLabel jTPasaje4;
    private javax.swing.JLabel jTPasaje5;
    private javax.swing.JLabel jTPasaje6;
    private javax.swing.JLabel jTPasaje7;
    private javax.swing.JLabel jTPasaje8;
    private javax.swing.JLabel jTPasaje9;
    private javax.swing.JPanel panelLateral1Ciudad;
    private javax.swing.JPanel panelLateral2Ciudad;
    public static javax.swing.JTextField precioAlojT;
    public static javax.swing.JTextField precioPasajeT;
    public static javax.swing.JTextField precioTotal;
    public static javax.swing.JLabel temporada1;
    public static javax.swing.JLabel temporada2;
    public static javax.swing.JLabel temporada3;
    // End of variables declaration//GEN-END:variables

    public static void bloquearCampos() {
        jBA.setEnabled(false);
        jBCD.setEnabled(false);
        jBP.setEnabled(false);
        jLAclaracion1.setVisible(false);
        checkIN.setEnabled(false);
        checkOUT.setEnabled(false);
        jTFCantidadPasajeros.setEnabled(false);
        jTFCantidadPasajeros.setEditable(false);
    }

    public static void limpiarCampos() {
        //jTFCO.setText("");
        jTFCD.setText("");
        jTFTP.setText("");
        jTFIP.setText("");
        jTFAl1.setText("");
        jTFAl2.setText("");
        jTFAl3.setText("");
        checkIN.cleanup();
        checkOUT.cleanup();
        temporada1.setVisible(false);
        temporada2.setVisible(false);
        temporada3.setVisible(false);
        jTFCantidadPasajeros.setText("");
        jLTipoTemporada.setText("");
    }

    private Double calcularTemporada(Double total, Date inicio) {
        switch (inicio.getMonth()) {
            case 0:
                total = total * 1.3;
                temporada1.setVisible(true);
                jLTipoTemporada.setText("Temporada Alta");
                return total;
            case 1:
                total = total * 1.15;
                temporada2.setVisible(true);
                jLTipoTemporada.setText("Temporada Media");
                return total;
            case 5:
                total = total * 1.3;
                temporada1.setVisible(true);
                jLTipoTemporada.setText("Temporada Alta");
                return total;
            case 6:
                total = total * 1.15;
                temporada2.setVisible(true);
                jLTipoTemporada.setText("Temporada Media");
                return total;
            default:
                temporada3.setVisible(true);
                jLTipoTemporada.setText("Temporada Baja");
                return total;
        }
    }
}
