package Vistas;

import Popups.*;
import AccesoADatos.*;
import Entidades.*;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Susana
 */
public class VentanaPaquete extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaPaquete
     */
    public VentanaPaquete() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana
        limpiarCampos();
        desactivarCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelLateral2Ciudad = new javax.swing.JPanel();
        closeCiudad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelLateral1Ciudad = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLIdPaquete = new javax.swing.JLabel();
        jTFIdPaquete = new javax.swing.JTextField();
        buscarPaquete = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jBotonBuscar = new javax.swing.JButton();
        jBotonEliminar = new javax.swing.JButton();
        jBotonActivar = new javax.swing.JButton();
        jLCO = new javax.swing.JLabel();
        jTFCO = new javax.swing.JTextField();
        jLCD = new javax.swing.JLabel();
        jTFCD = new javax.swing.JTextField();
        jTFTransporte = new javax.swing.JTextField();
        jLTransporte = new javax.swing.JLabel();
        jLAlojamiento = new javax.swing.JLabel();
        jTFAlojamiento = new javax.swing.JTextField();
        jLServicio = new javax.swing.JLabel();
        jTFServicio = new javax.swing.JTextField();
        jLCheckIN = new javax.swing.JLabel();
        jTFCheckIn = new javax.swing.JTextField();
        jLCheckOut = new javax.swing.JLabel();
        jTFCheckOut = new javax.swing.JTextField();
        jLTotal = new javax.swing.JLabel();
        JTFTotal = new javax.swing.JTextField();
        jLTipoTemporada = new javax.swing.JLabel();
        jTFnPersonas = new javax.swing.JTextField();
        jLnPersonas = new javax.swing.JLabel();
        jTFTipoTemporada = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setTitle("Paquete");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jDesktopPane1.setAlignmentX(0.0F);
        jDesktopPane1.setAlignmentY(0.0F);
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(800, 600));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(800, 600));

        panelLateral2Ciudad.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout panelLateral2CiudadLayout = new javax.swing.GroupLayout(panelLateral2Ciudad);
        panelLateral2Ciudad.setLayout(panelLateral2CiudadLayout);
        panelLateral2CiudadLayout.setHorizontalGroup(
            panelLateral2CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        panelLateral2CiudadLayout.setVerticalGroup(
            panelLateral2CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jDesktopPane1.add(panelLateral2Ciudad);
        panelLateral2Ciudad.setBounds(0, 171, 229, 450);

        closeCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flechaAtras.png"))); // NOI18N
        closeCiudad.setText("Atrás");
        closeCiudad.setAlignmentY(0.0F);
        closeCiudad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeCiudad.setBorderPainted(false);
        closeCiudad.setContentAreaFilled(false);
        closeCiudad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCiudadActionPerformed(evt);
            }
        });
        jDesktopPane1.add(closeCiudad);
        closeCiudad.setBounds(670, 20, 90, 38);

        jLabel1.setFont(new java.awt.Font("Broadway", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAQUETES");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(370, 50, 230, 50);

        panelLateral1Ciudad.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo2.png"))); // NOI18N

        javax.swing.GroupLayout panelLateral1CiudadLayout = new javax.swing.GroupLayout(panelLateral1Ciudad);
        panelLateral1Ciudad.setLayout(panelLateral1CiudadLayout);
        panelLateral1CiudadLayout.setHorizontalGroup(
            panelLateral1CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateral1CiudadLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelLateral1CiudadLayout.setVerticalGroup(
            panelLateral1CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateral1CiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.add(panelLateral1Ciudad);
        panelLateral1Ciudad.setBounds(0, 0, 229, 172);

        jLIdPaquete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLIdPaquete.setText("Id Paquete: ");
        jDesktopPane1.add(jLIdPaquete);
        jLIdPaquete.setBounds(270, 180, 100, 17);

        jTFIdPaquete.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTFIdPaquete.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTFIdPaquete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFIdPaqueteKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTFIdPaquete);
        jTFIdPaquete.setBounds(360, 180, 104, 20);

        buscarPaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        buscarPaquete.setBorderPainted(false);
        buscarPaquete.setContentAreaFilled(false);
        buscarPaquete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPaqueteActionPerformed(evt);
            }
        });
        jDesktopPane1.add(buscarPaquete);
        buscarPaquete.setBounds(470, 170, 30, 30);

        clearButton.setText("Limpiar");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jDesktopPane1.add(clearButton);
        clearButton.setBounds(680, 220, 90, 32);

        jBotonBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonBuscar.setText("Buscar");
        jBotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonBuscar);
        jBotonBuscar.setBounds(680, 180, 90, 31);

        jBotonEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonEliminar.setText("Eliminar");
        jBotonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEliminarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonEliminar);
        jBotonEliminar.setBounds(590, 530, 100, 31);

        jBotonActivar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonActivar.setText("Activar");
        jBotonActivar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonActivarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBotonActivar);
        jBotonActivar.setBounds(700, 530, 90, 31);

        jLCO.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCO.setText("Ciudad Origen:");
        jDesktopPane1.add(jLCO);
        jLCO.setBounds(260, 220, 120, 17);

        jTFCO.setEditable(false);
        jTFCO.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTFCO);
        jTFCO.setBounds(390, 220, 260, 23);

        jLCD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCD.setText("Ciudad Destino:");
        jDesktopPane1.add(jLCD);
        jLCD.setBounds(260, 250, 120, 17);

        jTFCD.setEditable(false);
        jTFCD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTFCD);
        jTFCD.setBounds(390, 250, 260, 23);

        jTFTransporte.setEditable(false);
        jTFTransporte.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTFTransporte);
        jTFTransporte.setBounds(390, 280, 260, 23);

        jLTransporte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTransporte.setText("Transporte:");
        jDesktopPane1.add(jLTransporte);
        jLTransporte.setBounds(260, 280, 120, 17);

        jLAlojamiento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLAlojamiento.setText("Alojamiento:");
        jDesktopPane1.add(jLAlojamiento);
        jLAlojamiento.setBounds(260, 310, 120, 17);

        jTFAlojamiento.setEditable(false);
        jTFAlojamiento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTFAlojamiento);
        jTFAlojamiento.setBounds(390, 310, 260, 23);

        jLServicio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLServicio.setText("Servicio:");
        jDesktopPane1.add(jLServicio);
        jLServicio.setBounds(260, 340, 120, 17);

        jTFServicio.setEditable(false);
        jTFServicio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTFServicio);
        jTFServicio.setBounds(390, 340, 260, 23);

        jLCheckIN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCheckIN.setText("Check In:");
        jDesktopPane1.add(jLCheckIN);
        jLCheckIN.setBounds(260, 370, 120, 17);

        jTFCheckIn.setEditable(false);
        jTFCheckIn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTFCheckIn);
        jTFCheckIn.setBounds(390, 370, 260, 23);

        jLCheckOut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCheckOut.setText("Check Out:");
        jDesktopPane1.add(jLCheckOut);
        jLCheckOut.setBounds(260, 400, 120, 17);

        jTFCheckOut.setEditable(false);
        jTFCheckOut.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTFCheckOut);
        jTFCheckOut.setBounds(390, 400, 260, 23);

        jLTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTotal.setText("Precio:    $");
        jDesktopPane1.add(jLTotal);
        jLTotal.setBounds(450, 490, 120, 17);

        JTFTotal.setEditable(false);
        JTFTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(JTFTotal);
        JTFTotal.setBounds(530, 490, 130, 23);

        jLTipoTemporada.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTipoTemporada.setText("Temporada:");
        jDesktopPane1.add(jLTipoTemporada);
        jLTipoTemporada.setBounds(260, 430, 120, 17);

        jTFnPersonas.setEditable(false);
        jTFnPersonas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTFnPersonas);
        jTFnPersonas.setBounds(630, 430, 40, 23);

        jLnPersonas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLnPersonas.setText("Personas:");
        jDesktopPane1.add(jLnPersonas);
        jLnPersonas.setBounds(550, 430, 120, 17);

        jTFTipoTemporada.setEditable(false);
        jTFTipoTemporada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTFTipoTemporada);
        jTFTipoTemporada.setBounds(390, 430, 150, 23);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCiudadActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeCiudadActionPerformed

    private void jTFIdPaqueteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdPaqueteKeyTyped
        char caracter = evt.getKeyChar();
        if ((caracter < '0' || caracter > '9') && (caracter != KeyEvent.VK_BACKSPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFIdPaqueteKeyTyped

    private void buscarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPaqueteActionPerformed
        jDesktopPane1.repaint();
        popupPaqueteBuscar popupPaqueteBuscar = new popupPaqueteBuscar();
        popupPaqueteBuscar.setVisible(true);
        jDesktopPane1.add(popupPaqueteBuscar);
        jDesktopPane1.moveToFront(popupPaqueteBuscar);
    }//GEN-LAST:event_buscarPaqueteActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        limpiarCampos();
        desactivarCampos();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jBotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEliminarActionPerformed
        Paquete_Data p = new Paquete_Data();
        p.eliminarPaquete(Integer.parseInt(jTFIdPaquete.getText()));
        clearButtonActionPerformed(evt);
    }//GEN-LAST:event_jBotonEliminarActionPerformed

    private void jBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarActionPerformed
        Paquete_Data p = new Paquete_Data();
        Paquete paquete = new Paquete();
        try {
            paquete = p.buscarPaquete2(Integer.parseInt(jTFIdPaquete.getText()));
            jTFCO.setText(paquete.getOrigen().toString());
            jTFCD.setText(paquete.getDestino().toString());
            jTFTransporte.setText(paquete.getPasaje().getTipoTransporte());
            jTFAlojamiento.setText(paquete.getAlojamiento().getTipoAlojamiento());
            jTFServicio.setText(paquete.getAlojamiento().getTipoServicio());
            jTFCheckIn.setText(paquete.getAlojamiento().getFechaIn().toString());
            jTFCheckOut.setText(paquete.getAlojamiento().getFechaOut().toString());
            jTFnPersonas.setText(paquete.getnPersonas()+"");
            jTFTipoTemporada.setText(paquete.getTipoTemporada());
            JTFTotal.setText(paquete.getPrecio().toString());
            jBotonEliminar.setEnabled(true);
        }catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "Debe ingresar un ID de paquete");
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Debe ingresar un ID de paquete");
        }
    }//GEN-LAST:event_jBotonBuscarActionPerformed

    private void jBotonActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonActivarActionPerformed
        jDesktopPane1.repaint();
        popupPaqueteActivar popupPaqueteActivar = new popupPaqueteActivar();
        popupPaqueteActivar.setVisible(true);
        jDesktopPane1.add(popupPaqueteActivar);
        jDesktopPane1.moveToFront(popupPaqueteActivar);
    }//GEN-LAST:event_jBotonActivarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField JTFTotal;
    private javax.swing.JButton buscarPaquete;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeCiudad;
    private javax.swing.JButton jBotonActivar;
    private javax.swing.JButton jBotonBuscar;
    private javax.swing.JButton jBotonEliminar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLAlojamiento;
    private javax.swing.JLabel jLCD;
    private javax.swing.JLabel jLCO;
    private javax.swing.JLabel jLCheckIN;
    private javax.swing.JLabel jLCheckOut;
    private javax.swing.JLabel jLIdPaquete;
    private javax.swing.JLabel jLServicio;
    private javax.swing.JLabel jLTipoTemporada;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLTransporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLnPersonas;
    public static javax.swing.JTextField jTFAlojamiento;
    public static javax.swing.JTextField jTFCD;
    public static javax.swing.JTextField jTFCO;
    public static javax.swing.JTextField jTFCheckIn;
    public static javax.swing.JTextField jTFCheckOut;
    public static javax.swing.JTextField jTFIdPaquete;
    public static javax.swing.JTextField jTFServicio;
    public static javax.swing.JTextField jTFTipoTemporada;
    public static javax.swing.JTextField jTFTransporte;
    public static javax.swing.JTextField jTFnPersonas;
    private javax.swing.JPanel panelLateral1Ciudad;
    private javax.swing.JPanel panelLateral2Ciudad;
    // End of variables declaration//GEN-END:variables

    public void desactivarCampos() {
        jBotonEliminar.setEnabled(false);
    }

    public void activarCampos() {

    }

    public void limpiarCampos() {
        jTFIdPaquete.setText("");
        jTFCO.setText("");
        jTFCD.setText("");
        jTFTransporte.setText("");
        jTFAlojamiento.setText("");
        jTFServicio.setText("");
        jTFCheckIn.setText("");
        jTFCheckOut.setText("");
        jTFnPersonas.setText("");
        jTFTipoTemporada.setText("");
        JTFTotal.setText("");
    }
}
