package Vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import AccesoADatos.*;
import Entidades.*;

/**
 *
 * @author Susana
 */
public class VentanaAlojamiento extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private Alojamiento_Data alojamientoData = new Alojamiento_Data();
    private Alojamiento alojamiento = null;
    private Ciudad ciudad = new Ciudad();
    private Ciudad_Data ciudadData = new Ciudad_Data();

    /**
     * Creates new form Alojamiento
     */
    public VentanaAlojamiento() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null); //Elimina encabezado de ventana
        cargarComboTipoAlojamiento();
        cargarComboTipoServ();
        limpiarCampos();
        cabeceraTabla();
        jBotonGuardar.setEnabled(false);
        jBotonEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLId = new javax.swing.JLabel();
        jTId = new javax.swing.JTextField();
        jBotonBuscar = new javax.swing.JButton();
        jTipoAloj = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLTipoServ = new javax.swing.JLabel();
        jLImporte = new javax.swing.JLabel();
        jLCiudadDestino = new javax.swing.JLabel();
        jTImporteDiario = new javax.swing.JTextField();
        jTIdCiudadDest = new javax.swing.JTextField();
        jBotonModificar = new javax.swing.JButton();
        jBotonNuevo = new javax.swing.JButton();
        jBotonEliminar = new javax.swing.JButton();
        jBotonGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaAlojamiento = new javax.swing.JTable();
        jComboTipoAloj = new javax.swing.JComboBox<>();
        jComboTipoServ = new javax.swing.JComboBox<>();
        jDateFechaSalida = new com.toedter.calendar.JDateChooser();
        jDateFechaIng = new com.toedter.calendar.JDateChooser();
        jLNombreCiudad = new javax.swing.JLabel();
        jTNombreCiudad = new javax.swing.JTextField();
        closeCiudad = new javax.swing.JButton();
        panelLateral1Ciudad = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelLateral2Ciudad = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setTitle("Alojamiento");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLId.setText("Id Alojamiento");
        getContentPane().add(jLId);
        jLId.setBounds(300, 70, 99, 17);

        jTId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jTId);
        jTId.setBounds(460, 60, 72, 23);

        jBotonBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonBuscar.setText("Buscar");
        jBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBotonBuscar);
        jBotonBuscar.setBounds(710, 380, 79, 33);

        jTipoAloj.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTipoAloj.setText("Tipo Alojamiento");
        getContentPane().add(jTipoAloj);
        jTipoAloj.setBounds(300, 110, 116, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Fecha Ingreso");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 190, 101, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Fecha Salida");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 220, 89, 17);

        jLTipoServ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTipoServ.setText("Tipo Servicio");
        getContentPane().add(jLTipoServ);
        jLTipoServ.setBounds(300, 150, 92, 17);

        jLImporte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLImporte.setText("Importe Diario: $");
        getContentPane().add(jLImporte);
        jLImporte.setBounds(300, 260, 115, 17);

        jLCiudadDestino.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLCiudadDestino.setText("Id Ciudad Destino");
        getContentPane().add(jLCiudadDestino);
        jLCiudadDestino.setBounds(260, 290, 124, 17);

        jTImporteDiario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jTImporteDiario);
        jTImporteDiario.setBounds(470, 250, 132, 23);

        jTIdCiudadDest.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jTIdCiudadDest);
        jTIdCiudadDest.setBounds(430, 290, 76, 23);

        jBotonModificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonModificar.setText("Modificar");
        jBotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jBotonModificar);
        jBotonModificar.setBounds(460, 510, 96, 33);

        jBotonNuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonNuevo.setText("Nuevo");
        jBotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBotonNuevo);
        jBotonNuevo.setBounds(260, 510, 76, 33);

        jBotonEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonEliminar.setText("Eliminar");
        jBotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBotonEliminar);
        jBotonEliminar.setBounds(610, 510, 86, 33);

        jBotonGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonGuardar.setText("Guardar");
        jBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBotonGuardar);
        jBotonGuardar.setBounds(360, 510, 87, 33);

        jScrollPane2.setViewportView(jTablaAlojamiento);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(237, 326, 480, 145);

        jComboTipoAloj.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jComboTipoAloj);
        jComboTipoAloj.setBounds(460, 100, 147, 27);

        jComboTipoServ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jComboTipoServ);
        jComboTipoServ.setBounds(430, 140, 176, 27);
        getContentPane().add(jDateFechaSalida);
        jDateFechaSalida.setBounds(420, 220, 164, 29);
        getContentPane().add(jDateFechaIng);
        jDateFechaIng.setBounds(470, 180, 164, 29);

        jLNombreCiudad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLNombreCiudad.setText("Nombre Ciudad: ");
        getContentPane().add(jLNombreCiudad);
        jLNombreCiudad.setBounds(510, 280, 116, 17);

        jTNombreCiudad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jTNombreCiudad);
        jTNombreCiudad.setBounds(640, 280, 132, 23);

        closeCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/flechaAtras.png"))); // NOI18N
        closeCiudad.setText("Atrás");
        closeCiudad.setAlignmentY(0.0F);
        closeCiudad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        closeCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(closeCiudad);
        closeCiudad.setBounds(670, 20, 90, 38);

        panelLateral1Ciudad.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo2.png"))); // NOI18N

        javax.swing.GroupLayout panelLateral1CiudadLayout = new javax.swing.GroupLayout(panelLateral1Ciudad);
        panelLateral1Ciudad.setLayout(panelLateral1CiudadLayout);
        panelLateral1CiudadLayout.setHorizontalGroup(
            panelLateral1CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        panelLateral1CiudadLayout.setVerticalGroup(
            panelLateral1CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );

        getContentPane().add(panelLateral1Ciudad);
        panelLateral1Ciudad.setBounds(0, 0, 229, 171);

        panelLateral2Ciudad.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout panelLateral2CiudadLayout = new javax.swing.GroupLayout(panelLateral2Ciudad);
        panelLateral2Ciudad.setLayout(panelLateral2CiudadLayout);
        panelLateral2CiudadLayout.setHorizontalGroup(
            panelLateral2CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        panelLateral2CiudadLayout.setVerticalGroup(
            panelLateral2CiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(panelLateral2Ciudad);
        panelLateral2Ciudad.setBounds(0, 171, 229, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonModificarActionPerformed
        Alojamiento alojamiento = new Alojamiento();
        try {
            Integer id = Integer.parseInt(jTId.getText());
            int idCD = Integer.parseInt(jTIdCiudadDest.getText());
            TipoAloj tipoAloj = (TipoAloj) jComboTipoAloj.getSelectedItem();
            String tipoAl = tipoAloj.name();//parseo tipo tipoAlojamiento a String 
            TipoServ serv = (TipoServ) jComboTipoServ.getSelectedItem();
            String servicio = serv.name();//parseo tipo tipoServicio a String;
            LocalDate fecIng = jDateFechaIng.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();// como declarar estas variables
            LocalDate fecSal = jDateFechaSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Boolean estado = true;
            double importe = Double.parseDouble(jTImporteDiario.getText());
            Ciudad cD = ciudadData.buscarCiudad(idCD);
            jTNombreCiudad.setText(cD.getNombre());
            Alojamiento aloja = alojamientoData.buscarAlojamiento(id);
            if (id == aloja.getIdAlojamiento()) {
                aloja.setTipoAlojamiento(tipoAl);
                aloja.setFechaIn(fecIng);
                aloja.setFechaOut(fecSal);
                aloja.setImporteDiario(importe);
                aloja.setCiudadDest(cD);
                aloja.setTipoServicio(servicio);
                aloja.setEstado(estado);

                alojamientoData.modificarAlojamiento(aloja);
            }
            jBotonNuevo.setEnabled(true);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "error" + ex);
        }

    }//GEN-LAST:event_jBotonModificarActionPerformed

    private void jBotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonNuevoActionPerformed
        activarCampos();
        limpiarCampos();
        alojamiento = null;
        jTId.setEnabled(false);
        jBotonNuevo.setEnabled(true);
        jBotonGuardar.setEnabled(true);
        jBotonEliminar.setEnabled(false);
        jBotonModificar.setEnabled(false);


    }//GEN-LAST:event_jBotonNuevoActionPerformed

    private void jBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarActionPerformed
        try {
            activarCampos();
            Alojamiento alojamiento = new Alojamiento();
            int id = Integer.parseInt(jTId.getText());
            String obtenertipoaloj, obtenerTipoServ;
            alojamiento = alojamientoData.buscarAlojamiento(id);
            if (alojamiento != null) {
                obtenertipoaloj = alojamiento.getTipoAlojamiento();
                obtenerTipoServ = alojamiento.getTipoServicio();
                jDateFechaIng.setDate(java.sql.Date.valueOf(alojamiento.getFechaIn()));
                jDateFechaSalida.setDate(java.sql.Date.valueOf(alojamiento.getFechaOut()));
                jTImporteDiario.setText(alojamiento.getImporteDiario() + "");
                jTIdCiudadDest.setText(alojamiento.getCiudadDest().getIdCiudad() + "");
                ciudad = ciudadData.buscarCiudad(alojamiento.getCiudadDest().getIdCiudad());
                jTNombreCiudad.setText(ciudad.getNombre());
                jComboTipoAloj.getModel().setSelectedItem(alojamiento.getTipoAlojamiento());
                jComboTipoServ.getModel().setSelectedItem(alojamiento.getTipoServicio());
                //CARGA LA TABLA CON LOS DATOS DEL FORMULARIO
                Object[] fila = {id, obtenertipoaloj, obtenerTipoServ, alojamiento.getFechaIn(), alojamiento.getFechaOut(), alojamiento.getImporteDiario(), ciudad.getNombre()};
                modelo.addRow(fila);
                jTablaAlojamiento.repaint();
                jBotonGuardar.setEnabled(true);
                jBotonEliminar.setEnabled(true);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar solo números para el Id ");
            jTId.requestFocus();
            limpiarCampos();
            jBotonGuardar.setEnabled(false);
        } catch (NullPointerException ex) {
            jTId.setText("");
            jBotonGuardar.setEnabled(false);
        }
        jTId.requestFocus();
        jBotonNuevo.setEnabled(true);
        jBotonGuardar.setEnabled(false);

    }//GEN-LAST:event_jBotonBuscarActionPerformed

    private void jBotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonGuardarActionPerformed

        jTId.setEnabled(false);
        TipoAloj tipoAloj = (TipoAloj) jComboTipoAloj.getSelectedItem();
        String tipoAl = tipoAloj.name();//parseo tipo tipoAlojamiento a String 
        TipoServ serv = (TipoServ) jComboTipoServ.getSelectedItem();
        String servicio = serv.name();//parseo tipo tipoAlojamiento a String 
        LocalDate fecIng = jDateFechaIng.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();// como declarar estas variables
        LocalDate fecSal = jDateFechaSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Boolean estado = true;
        double importe = Double.parseDouble(jTImporteDiario.getText());
        int destino = Integer.parseInt(jTIdCiudadDest.getText());
        Ciudad ciudadDes = ciudadData.buscarCiudad(destino);
        if (alojamiento == null) {
            alojamiento = new Alojamiento(tipoAl, fecIng, fecSal, estado, servicio, importe, ciudadDes);
            alojamientoData.guardarAlojamiento(alojamiento);
            jBotonNuevo.setSelected(false);
        }

        limpiarCampos();
        desactivarCampos();
        jTId.requestFocus();
        jTId.setEnabled(true);
        jBotonNuevo.setEnabled(true);
        jBotonModificar.setEnabled(true);

    }//GEN-LAST:event_jBotonGuardarActionPerformed

    private void jBotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEliminarActionPerformed
        int id = Integer.parseInt(jTId.getText());
        String TipoAlojamiento = (String) jComboTipoAloj.getSelectedItem();
        LocalDate fI = jDateFechaIng.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate fS = jDateFechaSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String tServ = (String) jComboTipoServ.getSelectedItem();
        Double importe = Double.parseDouble(jTImporteDiario.getText());
        int idCiudadD = Integer.parseInt(jTIdCiudadDest.getText());
        Ciudad ciu = ciudadData.buscarCiudad(idCiudadD);
        if (alojamiento == null) {
            alojamiento = new Alojamiento(TipoAlojamiento, fI, fS, false, tServ, importe, ciu);
            int respuesta = JOptionPane.showConfirmDialog(null, "Esta por borrar un Alojamienot ¿Quieres continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                alojamientoData.eliminarAlojamiento(id);
                limpiarCampos();
                activarCampos();
                jTId.requestFocus();
            }
        }
    }//GEN-LAST:event_jBotonEliminarActionPerformed

    private void closeCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCiudadActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeCiudadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeCiudad;
    private javax.swing.JButton jBotonBuscar;
    private javax.swing.JButton jBotonEliminar;
    private javax.swing.JButton jBotonGuardar;
    private javax.swing.JButton jBotonModificar;
    private javax.swing.JButton jBotonNuevo;
    private javax.swing.JComboBox<TipoAloj> jComboTipoAloj;
    private javax.swing.JComboBox<TipoServ> jComboTipoServ;
    private com.toedter.calendar.JDateChooser jDateFechaIng;
    private com.toedter.calendar.JDateChooser jDateFechaSalida;
    private javax.swing.JLabel jLCiudadDestino;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLImporte;
    private javax.swing.JLabel jLNombreCiudad;
    private javax.swing.JLabel jLTipoServ;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTId;
    private javax.swing.JTextField jTIdCiudadDest;
    private javax.swing.JTextField jTImporteDiario;
    private javax.swing.JTextField jTNombreCiudad;
    private javax.swing.JTable jTablaAlojamiento;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jTipoAloj;
    private javax.swing.JPanel panelLateral1Ciudad;
    private javax.swing.JPanel panelLateral2Ciudad;
    // End of variables declaration//GEN-END:variables

    private void cargarComboTipoAlojamiento() {
        jComboTipoAloj.addItem(TipoAloj.ELIJA);
        jComboTipoAloj.addItem(TipoAloj.HOTEL);
        jComboTipoAloj.addItem(TipoAloj.HOSTEL);
        jComboTipoAloj.addItem(TipoAloj.HOSTERIA);
        jComboTipoAloj.addItem(TipoAloj.DEPARTAMENTO);
        jComboTipoAloj.addItem(TipoAloj.CABAÑA);
        jComboTipoAloj.addItem(TipoAloj.BUNGALOWS);

    }

    private void cargarComboTipoServ() {
        jComboTipoServ.addItem(TipoServ.ELIJA);
        jComboTipoServ.addItem(TipoServ.DESAYUNO);
        jComboTipoServ.addItem(TipoServ.DESAYUNO_ALMUERZO);
        jComboTipoServ.addItem(TipoServ.DESAYUNO_CENA);
        jComboTipoServ.addItem(TipoServ.MERIENDA_ALMUERZO);
        jComboTipoServ.addItem(TipoServ.MERIENDA_CENA);
        jComboTipoServ.addItem(TipoServ.PENSION_COMPLETA);

    }

    public void desactivarCampos() {

        jTId.setEnabled(false);
        jTImporteDiario.setEnabled(false);
        jTIdCiudadDest.setEnabled(false);

    }

    public void activarCampos() {
        jTId.setEnabled(true);
        jTImporteDiario.setEnabled(true);
        jTIdCiudadDest.setEnabled(true);

    }

    public void limpiarCampos() {
        jTId.setText("");
        jTImporteDiario.setText("");
        jTIdCiudadDest.setText("");
        jDateFechaIng.setDate(null);
        jDateFechaSalida.setDate(null);
        jComboTipoAloj.setSelectedIndex(0);
        jComboTipoServ.setSelectedIndex(0);
        jTNombreCiudad.setText("");
        modelo.setRowCount(0);

    }

    public void cabeceraTabla() {
        modelo.addColumn("ID");
        modelo.addColumn("Tipo Alojamiento");
        modelo.addColumn("Tipo Servicio");
        modelo.addColumn("Fecha Ingreso");
        modelo.addColumn("Fecha Salida");
        modelo.addColumn("Importe Diario $");
        modelo.addColumn("Ciudad Destino");
        jTablaAlojamiento.setModel(modelo);
    }

}
